### ISSUE TITLE
Add the ability for an attribute to "preserve" the property it is applied to 

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1127]
Similar to https://github.com/mono/linker/issues/1126. Once the `ValidationAttribute`s are being preserved, we need to preserve the property "getters" for any property marked with a ValidationAttribute.

`ComponentModel.DataAnnotations` will attempt to get the value of any property marked with a `ValidationAttribute`. Today, the getters are being stripped if they are not accessed statically.

See https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/Validator.cs#L515-L518.

We will need a way to preserve the property getters, or else this code will fail at runtime with:

```
Unhandled exception. System.ArgumentException: Property Get method was not found.
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.ComponentModel.DataAnnotations.Validator.GetPropertyValues(Object instance, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectPropertyValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.GetObjectValidationErrors(Object instance, ValidationContext validationContext, Boolean validateAllProperties, Boolean breakOnFirstError)
   at System.ComponentModel.DataAnnotations.Validator.TryValidateObject(Object instance, ValidationContext validationContext, ICollection`1 validationResults, Boolean validateAllProperties)
```

cc @vitek-karas

**Comment by MichalStrehovsky** [comment]
Note that ComponentModel allows things like [injecting attributes](https://stackoverflow.com/questions/12143650/how-to-add-property-level-attribute-to-the-typedescriptor-at-runtime) to things at runtime (without doing anything that looks like "linker unfriendly" code because we don't even need to grab a `PropertyInfo` from anywhere).

So if we are to go an implement this and then just say "oh yeah, the `instance.GetType().GetRuntimeProperties()` call in `GetPropertyValues` is actually linker safe, don't worry about it", we better be _really sure_ it's actually linker safe. Keeping just the attributed things doesn't make it linker safe.

**Comment by eerhardt** [comment]
> Note that ComponentModel allows things like injecting attributes to things at runtime

That is for `TypeDescriptor` in `System.ComponentModel.TypeConverter`, which is separate from the `Validator` in `System.ComponentModel.DataAnnotations`.

From all the code I saw in `Validator`, the only place that calls into `TypeDescriptor` is in the RangeAttribute in order to get a converter from a `string` to the type:

https://github.com/dotnet/runtime/blob/master/src/libraries/System.ComponentModel.Annotations/src/System/ComponentModel/DataAnnotations/RangeAttribute.cs#L203
