### ISSUE TITLE
.NET 5: Failed to resolve assembly: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1139]
Repro:

* Download and extract [linkertestcase-a79684b.zip](https://github.com/mono/linker/files/4523159/linkertestcase-a79684b.zip)

* Execute:

```shell
$ ./test.sh path/to/my/linker/executable
+ /Users/rolf/work/linker/master/artifacts/bin/Mono.Linker/Debug/netcoreapp3.0/illink -a ./asm//HelloForms.iOS.dll -p copy HelloForms.iOS -d ./asm/ -out linked/ -u copyused -c copyused --verbose --skip-unresolved false
Fatal error in IL Linker
Unhandled exception. Mono.Linker.LoadException: Error while processing references of 'HelloForms.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> Mono.Linker.LoadException: Error while processing references of 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters) in /Users/rolf/work/linker/master/src/linker/Linker/DirectoryAssemblyResolver.cs:line 63
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters) in /Users/rolf/work/linker/master/src/linker/Linker/AssemblyResolver.cs:line 117
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope) in /Users/rolf/work/linker/master/src/linker/Linker/LinkContext.cs:line 265
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope) in /Users/rolf/work/linker/master/src/linker/Linker/LinkContext.cs:line 273
   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker/LinkContext.cs:line 324
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/LoadReferencesStep.cs:line 52
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/LoadReferencesStep.cs:line 54
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/LoadReferencesStep.cs:line 56
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/LoadReferencesStep.cs:line 54
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/LoadReferencesStep.cs:line 56
   at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/LoadReferencesStep.cs:line 42
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context) in /Users/rolf/work/linker/master/src/linker/Linker.Steps/BaseStep.cs:line 61
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) in /Users/rolf/work/linker/master/src/linker/Linker/Pipeline.cs:line 133
   at Mono.Linker.Pipeline.Process(LinkContext context) in /Users/rolf/work/linker/master/src/linker/Linker/Pipeline.cs:line 126
   at Mono.Linker.Driver.Run(ILogger customLogger) in /Users/rolf/work/linker/master/src/linker/Linker/Driver.cs:line 607
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger) in /Users/rolf/work/linker/master/src/linker/Linker/Driver.cs:line 68
   at Mono.Linker.Driver.Main(String[] args) in /Users/rolf/work/linker/master/src/linker/Linker/Driver.cs:line 52
```

I'm not sure who is to blame here, but @akoeplinger suggested we should look at it: https://xamarinhq.slack.com/archives/CFB4MC864/p1587652331482300.

That said, one problem is that the exception trace is not helpful, because it looks like `Xamarin.Forms.Platform.iOS` references `System.Security.Permissions`, but that's not the case.

**Comment by marek-safar** [comment]
The problem with .NET Framework compatibility packages is tracked at https://github.com/dotnet/runtime/issues/35401
