### ISSUE TITLE
Error when printing stacktrace

### ISSUE THREAD

**Issue by pranavkm** [mono/linker#1306]
```
 Unhandled exception rendering component: Could not resolve type with token 0100007a from typeref (expected class 'System.Net.Security.SslClientAuthenticationOptions' in assembly 'System.Memory, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
System.TypeLoadException: Could not resolve type with token 0100007a from typeref (expected class 'System.Net.Security.SslClientAuthenticationOptions' in assembly 'System.Memory, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51')
   at System.Reflection.MonoMethodInfo.GetMethodInfo(IntPtr handle)
   at System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes()
   at System.Reflection.CustomAttribute.GetPseudoCustomAttributes(ICustomAttributeProvider obj, Type attributeType)
   at System.Reflection.CustomAttribute.GetCustomAttributesBase(ICustomAttributeProvider obj, Type attributeType, Boolean inheritedOnly)
   at System.Reflection.CustomAttribute.GetCustomAttributes(ICustomAttributeProvider obj, Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[StateMachineAttribute](MemberInfo element, Boolean inherit)
   at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat, StringBuilder sb)
   at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
   at System.Exception.GetStackTrace(Boolean needFileInfo)
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at System.IO.TextWriter.WriteLine(Object value)
   at System.IO.TextWriter.SyncTextWriter.WriteLine(Object value)
   at System.Console.WriteLine(Object value)
```

[_framework.zip](https://github.com/mono/linker/files/4858945/_framework.zip)

^ Bundled app. 

I saw this error when the server was unable.

**Comment by pranavkm** [comment]
Let me know if you need more details.

**Comment by marek-safar** [comment]
This should be duplicate of #1304 1304

**Comment by pranavkm** [comment]
Closing as dup.
