### ISSUE TITLE
Processed debug symbols aren't copied to the publish directory

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1331]
Repro:

[consoleapp-10efc6c.zip](https://github.com/mono/linker/files/4895462/consoleapp-10efc6c.zip)

Download, extract and run `make linked` to run the linked sample, and `make notlinked` to run the non-linked sample.

Expected result: a stack trace with file name and line number information should be shown.

```
$ make notlinked
/usr/local/share/dotnet/sdk/5.0.100-preview.7.20317.11/MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/local/share/dotnet/sdk/5.0.100-preview.7.20317.11/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/local/share/dotnet/sdk/5.0.100-preview.7.20317.11/dotnet.dll -maxcpucount -property:RuntimeIdentifier=osx-x64 -property:SelfContained=true -p:MonoAOT=true -p:VM=mono -p:PublishTrimmed=false -restore -target:Publish -verbosity:m /v:quiet /bl:consoleapp-notlinked.binlog ./myproject.csproj
** Executing app as-is
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
   at System.Environment.get_StackTrace()
   at App.Main() in /Users/rolf/test/dotnet/consoleapp/Program.cs:line 7

$ make linked
/usr/local/share/dotnet/sdk/5.0.100-preview.7.20317.11/MSBuild.dll -nologo -distributedlogger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,/usr/local/share/dotnet/sdk/5.0.100-preview.7.20317.11/dotnet.dll*Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingLogger,/usr/local/share/dotnet/sdk/5.0.100-preview.7.20317.11/dotnet.dll -maxcpucount -property:RuntimeIdentifier=osx-x64 -property:SelfContained=true -p:MonoAOT=true -p:VM=mono -p:PublishTrimmed=true -p:_ExtraTrimmerArgs=-b -restore -target:Publish -verbosity:m /v:quiet /bl:consoleapp-linked.binlog ./myproject.csproj
** Executing app as-is
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
   at System.Environment.get_StackTrace()
   at App.Main()
** Copying in the linked pdb
cp ./obj/Debug/netcoreapp5.0/osx-x64/linked/myproject.pdb ./bin/Debug/netcoreapp5.0/osx-x64/publish
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
   at System.Environment.get_StackTrace()
   at App.Main() in /Users/rolf/test/dotnet/consoleapp/Program.cs:line 7
```

The non-linked sample works (shows Program.cs:7), but the linked sample only works after copying the linked pdb into the publish directory.

**Comment by marek-safar** [comment]
@sbomer is this something what was fixed in the debugger SDK changes?

**Comment by sbomer** [comment]
Yes, this should be fixed with https://github.com/dotnet/sdk/pull/12144. The latest bits from dotnet/installer have the change - would you mind giving it a try @rolfbjarne?

**Comment by rolfbjarne** [comment]
> would you mind giving it a try @rolfbjarne?

Correct, this seems to be working now.
