### ISSUE TITLE
Removing attributes breaks when an assembly is set to "copy"

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1341]
Using the `ILLink.LinkAttributes.xml` file from https://github.com/dotnet/runtime/pull/39000 and linking the [CarChecker app](https://github.com/SteveSandersonMS/CarChecker/tree/net5), I'm getting the following error:

```
Mono.Linker.LinkerFatalErrorException: ILLinker: error IL1011: Failed to write 'obj\Release\net5.0\browser-wasm\linked\CarChecker.Client.dll
 ---> Mono.Cecil.ResolutionException: Failed to resolve System.ComponentModel.EditorBrowsableState
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeEnumValue(TypeReference enum_type, Object value)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeValue(TypeReference type, Object value)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeElement(TypeReference type, CustomAttributeArgument argument)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeConstructorArguments(CustomAttribute attribute)
   at Mono.Cecil.MetadataBuilder.GetCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider owner)
   at Mono.Cecil.MetadataBuilder.AddProperty(PropertyDefinition property)
   at Mono.Cecil.MetadataBuilder.AddProperties(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Cecil.AssemblyDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters) in F:\git\linker\src\linker\Linker.Steps\OutputStep.cs:line 127
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters) in F:\git\linker\src\linker\Linker.Steps\OutputStep.cs:line 129
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory) in F:\git\linker\src\linker\Linker.Steps\OutputStep.cs:line 111
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly) in F:\git\linker\src\linker\Linker.Steps\OutputStep.cs:line 146
   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly) in F:\git\linker\src\linker\Linker.Steps\OutputStep.cs:line 106
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context) in F:\git\linker\src\linker\Linker.Steps\BaseStep.cs:line 63
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) in F:\git\linker\src\linker\Linker\Pipeline.cs:line 135
   at Mono.Linker.Pipeline.Process(LinkContext context) in F:\git\linker\src\linker\Linker\Pipeline.cs:line 128
   at Mono.Linker.Driver.Run(ILogger customLogger) in F:\git\linker\src\linker\Linker\Driver.cs:line 707
```

The issue, as far as I can tell, is that the `ILLink.LinkAttributes.xml` file says to remove the `System.ComponentModel.EditorBrowsableAttribute`. However, we can't remove the attributes from the "application" assemblies - like `CarChecker.Client.dll` - because those assemblies are being passed to the linker with `-p copy`, which means they won't be updated/trimmed.

You can repro this with an app like:

```C#
using System.ComponentModel;

namespace ExperimentsApp
{
    [EditorBrowsable(EditorBrowsableState.Never)]
    class Program
    {
        static void Main(string[] args)
        {
            System.Console.WriteLine(new Program());
        }
    }
}
```

publish that app, and link it with the command line args:

```
-a ExperimentsApp
-p copy "ExperimentsApp"
-c link -u link
-d F:\AppModel\linker\ExperimentsApp\bin\Debug\net5.0\win-x64\publish\
-out F:\AppModel\linker\t\experiments
--link-attributes C:\temp\ILLink.LinkAttributes.wasm.xml
```

where `C:\temp\ILLink.LinkAttributes.wasm.xml` looks like:

```xml
<linker>
  <assembly fullname="*">

    <!-- Microsoft.ComponentModel -->
    <type fullname="System.ComponentModel.EditorBrowsableAttribute">
      <attribute internal="RemoveAttributeInstances" />
    </type>

  </assembly>
</linker>
```

@vitek-karas @marek-safar @tlakollo

**Comment by eerhardt** [comment]
Note that this is blocking https://github.com/dotnet/runtime/pull/39000 because it will cause Blazor applications to fail to publish with the above error until this is fixed.

**Comment by vitek-karas** [comment]
PR with the fix: https://github.com/mono/linker/pull/1344

**Comment by vitek-karas** [comment]
Note: I was not able to repro the failure - but I did repro wrong behavior of the linker producing invalid assemblies (assemblies with missing typerefs and so on). The fix should work in either case though.
