### ISSUE TITLE
Linker crashes on interop method with function pointers

### ISSUE THREAD

**Issue by jkotas** [mono/linker#1345]
```
 Mono.Linker.LinkerFatalErrorException: ILLinker: error IL1005: .Interop.Kernel32.EnumSystemLocalesEx(method,UInt32,Void*,IntPtr): Error processing method '.Interop.Kernel32.EnumSystemLocalesEx(method,UInt32,Void*,IntPtr)' in assembly 'System.Private.CoreLib.dll'
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.Steps.MarkStep.ProcessInteropMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
```
See https://github.com/dotnet/runtime/pull/39082 for repro

**Comment by marek-safar** [comment]
@MichalStrehovsky could you look into this?

/cc @vitek-karas

**Comment by RussKie** [comment]
I'm still hitting this in Microsoft.NET.Sdk.IL: 5.0.0-rc.1.20411.1, SDK: 5.0.100-preview.7.20356.2/5.0.100-preview.8.20359.7

How/where do I get the fixed version?

**Comment by vitek-karas** [comment]
@RussKie Do you still see the failure? I tried something similar with 5.0.100-rc.1.20453.7 and it worked.
If you still see a failure, could you please paste the exact error and what did you try?
