### ISSUE TITLE
Linker crashes when trimming csc

### ISSUE THREAD

**Issue by agocke** [mono/linker#1375]
Stack: 

```
         Fatal error in IL Linker
         Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
            at Mono.Linker.Steps.MarkStep.GetMethodWithNoParameters(TypeDefinition type, String methodname)
            at Mono.Linker.Steps.MarkStep.MarkTypeWithDebuggerDisplayAttribute(TypeDefinition type, CustomAttribute attribute)
            at Mono.Linker.Steps.MarkStep.MarkTypeSpecialCustomAttributes(TypeDefinition type)
            at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
            at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
            at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
            at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
            at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
            at Mono.Linker.Steps.MarkStep.Initialize()
            at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Main(String[] args)
```

SDK:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20371.1
 Commit:    d24cc8a10a
```

**Comment by agocke** [comment]
Note: only seems to happen with a release build. If I switch to `-c Debug` the linker succeeds.

**Comment by tlakollo** [comment]
Error occurs while linker is calling MarkTypeWithDebuggerDisplayAttribute() on type Microsoft.CodeAnalysis.CSharp.ConversionGroup, according to https://github.com/dotnet/roslyn/blob/master/src/Compilers/CSharp/Portable/BoundTree/ConversionGroup.cs file the attribute [DebuggerDisplay("{GetDebuggerDisplay(), nq}")] should keep the GetDebuggerDisplay method. But this method is surrounded by an #if DEBUG clause which explain why the Debug configuration does not fail.
