### ISSUE TITLE
Linq.Queryable.GroupBy doesn't work when using TrimMode=link

### ISSUE THREAD

**Issue by rolfbjarne** [mono/linker#1453]
Repro: 
[consoleapp-99c9d68.zip](https://github.com/mono/linker/files/5126317/consoleapp-99c9d68.zip)

Run `make linked` to run with `TrimMode=link`, and `make notlinked` to run the same command, except without setting `TrimMode`.

```shell
$ make linked
** Executing linked app
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
❌ failed: System.NotSupportedException: Collection is read-only.
   at System.SZArrayHelper.Clear[T]()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, String name, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, Boolean tailCall, IEnumerable`1 parameters)
   at System.Linq.Expressions.Expression.Lambda[TDelegate](Expression body, ParameterExpression[] parameters)
   at App.Main() in /Users/rolf/test/dotnet/consoleapp/Program.cs:line 18

$ make notlinked
** Executing notlinked app
bin/Debug/netcoreapp5.0/osx-x64/publish/myproject
✅ succeeded: hello hello
```

```shell
$ dotnet --version
5.0.100-rc.1.20414.5
```

**Comment by MichalStrehovsky** [comment]
Possibly dupe of #1398. Can you check the ILLinkTrim.xml file embedded in System.Private.CoreLib managed resources has the following comment: "GetActualImplementationForArrayGenericIListOrIReadOnlyListMethod depends on slots of these interfaces not changing"?

**Comment by marek-safar** [comment]
It really looks like a duplicate of #1398

**Comment by rolfbjarne** [comment]
> Can you check the ILLinkTrim.xml file embedded in System.Private.CoreLib managed resources has the following comment: "GetActualImplementationForArrayGenericIListOrIReadOnlyListMethod depends on slots of these interfaces not changing"?

Correct, the dotnet version I was using didn't have that comment, so I updated (to 5.0.100-rc.1.20426.3) and now that comment exist and the problem is gone.
