### ISSUE TITLE
Linker fails during publishing of the project

### ISSUE THREAD

**Issue by Denterl** [mono/linker#1508]
Hello,

Executing the line: `dotnet publish -c Release --self-contained=true` for version `5.0.100-rc.1.20452.10`
With the following settings in proj file:
```
<PublishTrimmed>true</PublishTrimmed>
<RuntimeIdentifier>win-x64</RuntimeIdentifier>
```

Returns the error: 
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues 
  Fatal error in IL Linker
  Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key '2' was not present in the dictionary.
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.ConstantExpressionMethodAnalyzer.GetLocalsValue(Int32 index, MethodBody body)
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.ConstantExpressionMethodAnalyzer.Analyze()
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.FindConstantExpressionsMethods(Collection`1 types)
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.FindConstantExpressionsMethods(Collection`1 types)
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

**Comment by vitek-karas** [comment]
@mateoatr are we confident that #1511 fixes this problem? If so - we should close this issue.

**Comment by mateoatr** [comment]
Yes, I think so. Closing.

**Comment by marek-safar** [comment]
I think this one might be worth backporting to 5.0

**Comment by pintset** [comment]
@mateoatr , @vitek-karas . The issue was reproduced on RC2: 5.0.100-rc.2.20479.15
Thought that fix will be included in the next RC.

**Comment by daz10000** [comment]
Yes, can confirm problem is there in `5.0.100-rc.2.20479.15` as well for my build.  Same error message.

**Comment by vitek-karas** [comment]
The change has been porter to 5.0 https://github.com/mono/linker/commit/98797dd6c2cc5c0c8042db5624e161177137711f
I validated that the code change is in the latest nightly build of 5.0 RTM SDK (didn't try to repro though).
It would be great if somebody who is hitting this problem could try with the latest 5.0 RTM SDK from https://github.com/dotnet/installer.

**Comment by pintset** [comment]
Cannot build with RTM:  error NU1102: Unable to find package Microsoft.NETCore.App.Runtime.win-x64 with version (= 5.0.0) 
What runtime version should I specify? This

**Comment by vitek-karas** [comment]
You're right, it's broken: https://github.com/dotnet/installer/issues/8882
It worked for me 2 days ago 😞

**Comment by pintset** [comment]
> You're right, it's broken: [dotnet/installer#8882](https://github.com/dotnet/installer/issues/8882)
> It worked for me 2 days ago 😞

@vitek-karas , Workaround was provided for the issue with package you've mentioned, which allowed me to test the issue we are discussing here.

Tried with TrimMode=Link - everything works fine
