### ISSUE TITLE
Add TypeDescriptor.GetConverter heuristic

### ISSUE THREAD

**Issue by kekekeks** [mono/linker#153]
`System.ComponentModel.TypeDescriptor.GetConverter` can't properly work if these types are linked away. And it's reflection based, so linker is unable to find any references.

For now we are using https://raw.githubusercontent.com/wieslawsoltes/Core2D/04f95ee8c83e1bc5d4246db805dedfaec3156e3d/apps/Core2D.Avalonia.NetCore/linker.xml configuration file, but that should be excluded on linker level, I think.

**Comment by JustArchi** [comment]
I think this is the same issue I stumbled on.

```
OnUnhandledException() No parameterless constructor defined for this object.
StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at System.ComponentModel.ReflectTypeDescriptionProvider.SearchIntrinsicTable(Hashtable table, Type callingType)
   at System.ComponentModel.ReflectTypeDescriptionProvider.ReflectedTypeData.GetConverter(Object instance)
   at System.ComponentModel.TypeDescriptor.TypeDescriptionNode.DefaultTypeDescriptor.System.ComponentModel.ICustomTypeDescriptor.GetConverter()
   at System.ComponentModel.TypeDescriptor.GetConverter(Type type)
   at NLog.Internal.PropertyHelper.TryTypeConverterConversion(Type type, String value, Object& newValue)
   at NLog.Internal.PropertyHelper.SetPropertyFromString(Object obj, String propertyName, String value, ConfigurationItemFactory configurationItemFactory)
```

Thanks for valid workaround.

**Comment by marek-safar** [comment]
Fixed in linker and Mono, for .NET Core fix you'll have to wait for next major version
