### ISSUE TITLE
IL1005 in blazor wasm

### ISSUE THREAD

**Issue by stefanloerwald** [mono/linker#1597]
```log
ILLink : error IL1005: DevExpress.Blazor.DataSourceLoadOptionsExtensions.AddToNameValueCollection<T>(NameValueCollection,String,T[]): Error processing method 'DevExpress.Blazor.DataSourceLoadOptionsExtensions.AddToNameValueCollection<T>(NameValueCollection,String,T[])' in assembly 'DevExpress.Blazor.dll' [/home/runner/work/path/to/project.csproj]
  Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: DevExpress.Blazor.DataSourceLoadOptionsExtensions.AddToNameValueCollection<T>(NameValueCollection,String,T[]): Error processing method 'DevExpress.Blazor.DataSourceLoadOptionsExtensions.AddToNameValueCollection<T>(NameValueCollection,String,T[])' in assembly 'DevExpress.Blazor.dll'
   ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.GetValueNodeFromGenericArgument(TypeReference genericArgument)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ProcessGenericArgumentDataFlow(GenericParameter genericParameter, TypeReference genericArgument, IMemberDefinition source)
     at Mono.Linker.Steps.MarkStep.MarkGenericArgumentConstructors(IGenericInstance instance, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.GetOriginalMethod(MethodReference method, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember)
     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction, MethodDefinition method, Boolean& requiresReflectionMethodBodyScanner)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
Error: /home/runner/.dotnet/sdk/5.0.100-rc.2.20479.15/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/home/runner/work/path/to/project.csproj]
Error: Process completed with exit code 1.
```

**Comment by mateoatr** [comment]
This should have been fixed by this PR: https://github.com/mono/linker/pull/1566/ Could you please try a master branch linker?
