### ISSUE TITLE
Crash writing native pdb's when server gc is enabled

### ISSUE THREAD

**Issue by mrvoorhe** [mono/linker#1598]
The short version is, with Server GC + Linking assemblies with native pdb's + link symbols enabled there is a random change of crashing while writing assemblies.

More details below.

After syncing up with upstream monolinker we turned on server gc in our UnityLinker.  A few days later we started seeing random crashes in our CI.

```
   Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Mono.Cecil.Pdb.ISymUnmanagedWriter2.Close()
   at Mono.Cecil.Pdb.ISymUnmanagedWriter2.Close()
   at Mono.Cecil.Pdb.SymWriter.Close()
   at Mono.Cecil.Pdb.NativePdbWriter.Dispose()
   at Mono.Cecil.ModuleWriter.Write(Mono.Cecil.ModuleDefinition, Mono.Disposable`1<System.IO.Stream>, Mono.Cecil.WriterParameters)
   at Mono.Cecil.ModuleWriter.WriteModule(Mono.Cecil.ModuleDefinition, Mono.Disposable`1<System.IO.Stream>, Mono.Cecil.WriterParameters)
   at Mono.Cecil.ModuleDefinition.Write(System.String, Mono.Cecil.WriterParameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(Mono.Cecil.AssemblyDefinition, System.String, Mono.Cecil.WriterParameters)
   at Mono.Linker.Steps.OutputStep.OutputAssembly(Mono.Cecil.AssemblyDefinition)
   at Mono.Linker.Steps.BaseStep.Process(Mono.Linker.LinkContext)
   at Unity.Linker.UnityPipeline.ProcessStep(Mono.Linker.LinkContext, Mono.Linker.Steps.IStep)
   at Mono.Linker.Pipeline.Process(Mono.Linker.LinkContext)
   at Unity.Linker.UnityDriver.UnityRun(Mono.Linker.ILogger)
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(Mono.Linker.ILogger)
   at Unity.Linker.UnityDriver.RunDriver()
   at Unity.Linker.Program.Main(System.String[])
```

We wrote a stress test to narrow in on just running UnityLinker and we were able to make the crash relatively reproducible.  Our stress test is in geared toward running il2cpp so I don't have a nice way to reproduce this crash with stock monolinker.  But what our stress test does is start N threads.  Each thread sets up it's own sandbox and compiles 5 or so assemblies into that directory and then runs UnityLinker out of process on the set of assemblies.  On my 8 core machine using 48 threads would reproduce the issue in 4-5 minutes at most.  Dropping down to 16 threads and the crash became somewhat rare but should still happen. 

Some random things we know so far.

* The crash will not happen if the symbols are portable pdbs instead of native pdbs.

* The crash happens on both .NET Core 3.1 and .NET FW when server gc is enabled.  Turn off server gc and the crash goes away for both.

**Comment by marek-safar** [comment]
@vitek-karas @MichalStrehovsky looks to me like some weird ServerGC and COM interference, thoughts?

**Comment by scott-ferguson-unity** [comment]
We were able to capture a crash in WinDbg during one of the linker stress test runs: 

```
 # Child-SP          RetAddr           Call Site
00 00000084`fbe7f0a8 00007fff`72ec0688 coreclr!SVR::gc_heap::generation_fragmentation+0x51 [f:\workspace\_work\1\s\src\gc\gc.cpp @ 31329] 
01 00000084`fbe7f0b0 00007fff`72eb3f3e coreclr!SVR::gc_heap::plan_phase+0x1344 [f:\workspace\_work\1\s\src\gc\gc.cpp @ 23477] 
02 00000084`fbe7f550 00007fff`72eb3ccc coreclr!SVR::gc_heap::gc1+0x14e [f:\workspace\_work\1\s\src\gc\gc.cpp @ 16348] 
03 00000084`fbe7f6b0 00007fff`72d6c27d coreclr!SVR::gc_heap::garbage_collect+0x12c0 [f:\workspace\_work\1\s\src\gc\gc.cpp @ 17982] 
04 00000084`fbe7f810 00007fff`72cc0e82 coreclr!SVR::gc_heap::gc_thread_function+0xab3ed [f:\workspace\_work\1\s\src\gc\gc.cpp @ 5814] 
05 00000084`fbe7f840 00007fff`72cd76f0 coreclr!SVR::gc_heap::gc_thread_stub+0xb2 [f:\workspace\_work\1\s\src\gc\gc.cpp @ 26058] 
06 (Inline Function) --------`-------- coreclr!standalone::`anonymous-namespace'::CreateNonSuspendableThread::__l2::<lambda_d40f6450dd6268468d0b61f834eb927e>::operator()+0x3e [f:\workspace\_work\1\s\src\vm\gcenv.ee.cpp @ 1363] 
07 00000084`fbe7fd90 00007ff8`022f7034 coreclr!<lambda_d40f6450dd6268468d0b61f834eb927e>::<lambda_invoker_cdecl>+0x50 [f:\workspace\_work\1\s\src\vm\gcenv.ee.cpp @ 1365] 
08 00000084`fbe7fdc0 00007ff8`03b5cec1 KERNEL32!BaseThreadInitThunk+0x14
09 00000084`fbe7fdf0 00000000`00000000 ntdll!RtlUserThreadStart+0x21

```
