### ISSUE TITLE
Linker failing in `dotnet/runtime` libraries tests

### ISSUE THREAD

**Issue by mdh1418** [mono/linker#1673]
When running the `dotnet/runtime` library tests for WebAssembly after adding `<PublishTrimmed>true</PublishTrimmed> ` to [tests.mobile.targets](https://github.com/dotnet/runtime/blob/master/eng/testing/tests.mobile.targets) under https://github.com/dotnet/runtime/pull/44751, several test suites hit the linker failure
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/__w/1/s/src/libraries/System.Reflection.Emit/tests/System.Reflection.Emit.Tests.csproj]
/__w/1/s/.dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/System.Reflection.Emit/tests/System.Reflection.Emit.Tests.csproj]
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/__w/1/s/src/libraries/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
/__w/1/s/.dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/System.Reflection.Emit.Lightweight/tests/System.Reflection.Emit.Lightweight.Tests.csproj]
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/__w/1/s/src/libraries/System.Reflection/tests/System.Reflection.Tests.csproj]
/__w/1/s/.dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/System.Reflection/tests/System.Reflection.Tests.csproj]
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/__w/1/s/src/libraries/System.ComponentModel.TypeConverter/tests/System.ComponentModel.TypeConverter.Tests.csproj]
/__w/1/s/.dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/System.Reflection.MetadataLoadContext/tests/System.Reflection.MetadataLoadContext.Tests.csproj]
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/__w/1/s/src/libraries/System.Runtime/tests/System.Runtime.Tests.csproj]
/__w/1/s/.dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/__w/1/s/src/libraries/System.Runtime/tests/System.Runtime.Tests.csproj]
```

When running of the test suites locally (`System.Reflection.Emit` for example), the error is
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/Users/mdhwang/runtime_wasm_clean/src/libraries/System.Reflection.Emit/tests/System.Reflection.Emit.Tests.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.InvalidOperationException: Operation is not valid due to the current state of the object.
     at Mono.Cecil.TypeSpecification.set_Scope(IMetadataScope value)
     at Mono.Linker.Steps.SweepStep.UpdateTypeScope(TypeReference type, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttributeArgument attributeArgument, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttributeArgument attributeArgument, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttributeArgument attributeArgument, AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.UpdateForwardedTypesScope(CustomAttribute attribute)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(ICustomAttributeProvider customAttributeProvider)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(Collection`1 methods)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(TypeDefinition typeDefinition)
     at Mono.Linker.Steps.SweepStep.UpdateCustomAttributesTypesScopes(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.ProcessAssemblyAction(AssemblyDefinition assembly)
     at Mono.Linker.Steps.SweepStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
/Users/mdhwang/runtime_wasm_clean/.dotnet/sdk/5.0.100/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(41,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [/Users/mdhwang/runtime_wasm_clean/src/libraries/System.Reflection.Emit/tests/System.Reflection.Emit.Tests.csproj]
```

Here is a zip containing the relevant files for a repro of the error.
[IL1012_libraries_tests.zip](https://github.com/mono/linker/files/5654914/IL1012_libraries_tests.zip)
With the command to run it (to be replaced with own local illink.dll)
```
/Users/mdhwang/runtime_wasm_clean/.dotnet/dotnet "/Users/mdhwang/.nuget/packages/microsoft.net.illink.tasks/6.0.0-alpha.1.20601.1/tools/net5.0/illink.dll" -a "Microsoft.DotNet.XHarness.TestRunners.Common.dll" -a "Microsoft.DotNet.XHarness.TestRunners.Xunit.dll" -a "Mono.Options.dll" -a "WasmTestRunner.dll" -a "Microsoft.VisualStudio.CodeCoverage.Shim.dll" -a "Microsoft.DotNet.XUnitExtensions.dll" -a "Microsoft.TestPlatform.CoreUtilities.dll" -a "Microsoft.TestPlatform.PlatformAbstractions.dll" -a "Microsoft.VisualStudio.TestPlatform.ObjectModel.dll" -a "Microsoft.TestPlatform.CommunicationUtilities.dll" -a "Microsoft.TestPlatform.CrossPlatEngine.dll" -a "Microsoft.TestPlatform.Utilities.dll" -a "Microsoft.VisualStudio.TestPlatform.Common.dll" -a "testhost.dll" -a "Newtonsoft.Json.dll" -a "NuGet.Frameworks.dll" -a "xunit.abstractions.dll" -a "xunit.assert.dll" -a "xunit.core.dll" -a "xunit.execution.dotnet.dll" -a "TestUtilities.dll" -a "System.Reflection.Emit.Tests.dll" -reference "Microsoft.DotNet.XHarness.TestRunners.Common.dll" -p copy "Microsoft.DotNet.XHarness.TestRunners.Common" -reference "Microsoft.DotNet.XHarness.TestRunners.Xunit.dll" -p copy "Microsoft.DotNet.XHarness.TestRunners.Xunit" -reference "Mono.Options.dll" -p copy "Mono.Options" -reference "WasmTestRunner.dll" -p copy "WasmTestRunner" -reference "Microsoft.VisualStudio.CodeCoverage.Shim.dll" -p copy "Microsoft.VisualStudio.CodeCoverage.Shim" -reference "Microsoft.DotNet.XUnitExtensions.dll" -p copy "Microsoft.DotNet.XUnitExtensions" -reference "Microsoft.TestPlatform.CoreUtilities.dll" -p copy "Microsoft.TestPlatform.CoreUtilities" -reference "Microsoft.TestPlatform.PlatformAbstractions.dll" -p copy "Microsoft.TestPlatform.PlatformAbstractions" -reference "Microsoft.VisualStudio.TestPlatform.ObjectModel.dll" -p copy "Microsoft.VisualStudio.TestPlatform.ObjectModel" -reference "Microsoft.TestPlatform.CommunicationUtilities.dll" -p copy "Microsoft.TestPlatform.CommunicationUtilities" -reference "Microsoft.TestPlatform.CrossPlatEngine.dll" -p copy "Microsoft.TestPlatform.CrossPlatEngine" -reference "Microsoft.TestPlatform.Utilities.dll" -p copy "Microsoft.TestPlatform.Utilities" -reference "Microsoft.VisualStudio.TestPlatform.Common.dll" -p copy "Microsoft.VisualStudio.TestPlatform.Common" -reference "testhost.dll" -p copy "testhost" -reference "Newtonsoft.Json.dll" -p copy "Newtonsoft.Json" -reference "NuGet.Frameworks.dll" -p copy "NuGet.Frameworks" -reference "xunit.abstractions.dll" -p copy "xunit.abstractions" -reference "xunit.assert.dll" -p copy "xunit.assert" -reference "xunit.core.dll" -p copy "xunit.core" -reference "xunit.execution.dotnet.dll" -p copy "xunit.execution.dotnet" -reference "TestUtilities.dll" -p copy "TestUtilities" -reference "System.Reflection.Emit.Tests.dll" -p copy "System.Reflection.Emit.Tests" -reference "Microsoft.CSharp.dll" -reference "Microsoft.VisualBasic.Core.dll" -reference "Microsoft.VisualBasic.dll" -reference "Microsoft.Win32.Primitives.dll" -reference "Microsoft.Win32.Registry.dll" -reference "System.AppContext.dll" -reference "System.Buffers.dll" -reference "System.Collections.Concurrent.dll" -reference "System.Collections.Immutable.dll" -reference "System.Collections.NonGeneric.dll" -reference "System.Collections.Specialized.dll" -reference "System.Collections.dll" -reference "System.ComponentModel.Annotations.dll" -reference "System.ComponentModel.DataAnnotations.dll" -reference "System.ComponentModel.EventBasedAsync.dll" -reference "System.ComponentModel.Primitives.dll" -reference "System.ComponentModel.TypeConverter.dll" -reference "System.ComponentModel.dll" -reference "System.Configuration.dll" -reference "System.Console.dll" -reference "System.Core.dll" -reference "System.Data.Common.dll" -reference "System.Data.DataSetExtensions.dll" -reference "System.Data.dll" -reference "System.Diagnostics.Contracts.dll" -reference "System.Diagnostics.Debug.dll" -reference "System.Diagnostics.DiagnosticSource.dll" -reference "System.Diagnostics.FileVersionInfo.dll" -reference "System.Diagnostics.Process.dll" -reference "System.Diagnostics.StackTrace.dll" -reference "System.Diagnostics.TextWriterTraceListener.dll" -reference "System.Diagnostics.Tools.dll" -reference "System.Diagnostics.TraceSource.dll" -reference "System.Diagnostics.Tracing.dll" -reference "System.Drawing.Primitives.dll" -reference "System.Drawing.dll" -reference "System.Dynamic.Runtime.dll" -reference "System.Formats.Asn1.dll" -reference "System.Globalization.Calendars.dll" -reference "System.Globalization.Extensions.dll" -reference "System.Globalization.dll" -reference "System.IO.Compression.Brotli.dll" -reference "System.IO.Compression.FileSystem.dll" -reference "System.IO.Compression.ZipFile.dll" -reference "System.IO.Compression.dll" -reference "System.IO.FileSystem.AccessControl.dll" -reference "System.IO.FileSystem.DriveInfo.dll" -reference "System.IO.FileSystem.Primitives.dll" -reference "System.IO.FileSystem.Watcher.dll" -reference "System.IO.FileSystem.dll" -reference "System.IO.IsolatedStorage.dll" -reference "System.IO.MemoryMappedFiles.dll" -reference "System.IO.Pipes.AccessControl.dll" -reference "System.IO.Pipes.dll" -reference "System.IO.UnmanagedMemoryStream.dll" -reference "System.IO.dll" -reference "System.Linq.Expressions.dll" -reference "System.Linq.Parallel.dll" -reference "System.Linq.Queryable.dll" -reference "System.Linq.dll" -reference "System.Memory.dll" -reference "System.Net.Http.Json.dll" -reference "System.Net.Http.dll" -reference "System.Net.HttpListener.dll" -reference "System.Net.Mail.dll" -reference "System.Net.NameResolution.dll" -reference "System.Net.NetworkInformation.dll" -reference "System.Net.Ping.dll" -reference "System.Net.Primitives.dll" -reference "System.Net.Quic.dll" -reference "System.Net.Requests.dll" -reference "System.Net.Security.dll" -reference "System.Net.ServicePoint.dll" -reference "System.Net.Sockets.dll" -reference "System.Net.WebClient.dll" -reference "System.Net.WebHeaderCollection.dll" -reference "System.Net.WebProxy.dll" -reference "System.Net.WebSockets.Client.dll" -reference "System.Net.WebSockets.dll" -reference "System.Net.dll" -reference "System.Numerics.Vectors.dll" -reference "System.Numerics.dll" -reference "System.ObjectModel.dll" -reference "System.Private.DataContractSerialization.dll" -reference "System.Private.Runtime.InteropServices.JavaScript.dll" -reference "System.Private.Uri.dll" -reference "System.Private.Xml.Linq.dll" -reference "System.Private.Xml.dll" -reference "System.Reflection.DispatchProxy.dll" -reference "System.Reflection.Emit.ILGeneration.dll" -reference "System.Reflection.Emit.Lightweight.dll" -reference "System.Reflection.Emit.dll" -reference "System.Reflection.Extensions.dll" -reference "System.Reflection.Metadata.dll" -reference "System.Reflection.Primitives.dll" -reference "System.Reflection.TypeExtensions.dll" -reference "System.Reflection.dll" -reference "System.Resources.Reader.dll" -reference "System.Resources.ResourceManager.dll" -reference "System.Resources.Writer.dll" -reference "System.Runtime.CompilerServices.Unsafe.dll" -reference "System.Runtime.CompilerServices.VisualC.dll" -reference "System.Runtime.Extensions.dll" -reference "System.Runtime.Handles.dll" -reference "System.Runtime.InteropServices.RuntimeInformation.dll" -reference "System.Runtime.InteropServices.dll" -reference "System.Runtime.Intrinsics.dll" -reference "System.Runtime.Loader.dll" -reference "System.Runtime.Numerics.dll" -reference "System.Runtime.Serialization.Formatters.dll" -reference "System.Runtime.Serialization.Json.dll" -reference "System.Runtime.Serialization.Primitives.dll" -reference "System.Runtime.Serialization.Xml.dll" -reference "System.Runtime.Serialization.dll" -reference "System.Runtime.dll" -reference "System.Security.AccessControl.dll" -reference "System.Security.Claims.dll" -reference "System.Security.Cryptography.Algorithms.dll" -reference "System.Security.Cryptography.Cng.dll" -reference "System.Security.Cryptography.Csp.dll" -reference "System.Security.Cryptography.Encoding.dll" -reference "System.Security.Cryptography.OpenSsl.dll" -reference "System.Security.Cryptography.Primitives.dll" -reference "System.Security.Cryptography.X509Certificates.dll" -reference "System.Security.Principal.Windows.dll" -reference "System.Security.Principal.dll" -reference "System.Security.SecureString.dll" -reference "System.Security.dll" -reference "System.ServiceModel.Web.dll" -reference "System.ServiceProcess.dll" -reference "System.Text.Encoding.CodePages.dll" -reference "System.Text.Encoding.Extensions.dll" -reference "System.Text.Encoding.dll" -reference "System.Text.Encodings.Web.dll" -reference "System.Text.Json.dll" -reference "System.Text.RegularExpressions.dll" -reference "System.Threading.Channels.dll" -reference "System.Threading.Overlapped.dll" -reference "System.Threading.Tasks.Dataflow.dll" -reference "System.Threading.Tasks.Extensions.dll" -reference "System.Threading.Tasks.Parallel.dll" -reference "System.Threading.Tasks.dll" -reference "System.Threading.Thread.dll" -reference "System.Threading.ThreadPool.dll" -reference "System.Threading.Timer.dll" -reference "System.Threading.dll" -reference "System.Transactions.Local.dll" -reference "System.Transactions.dll" -reference "System.ValueTuple.dll" -reference "System.Web.HttpUtility.dll" -reference "System.Web.dll" -reference "System.Windows.dll" -reference "System.Xml.Linq.dll" -reference "System.Xml.ReaderWriter.dll" -reference "System.Xml.Serialization.dll" -reference "System.Xml.XDocument.dll" -reference "System.Xml.XPath.XDocument.dll" -reference "System.Xml.XPath.dll" -reference "System.Xml.XmlDocument.dll" -reference "System.Xml.XmlSerializer.dll" -reference "System.Xml.dll" -reference "System.dll" -reference "WindowsBase.dll" -reference "mscorlib.dll" -reference "netstandard.dll" -reference "System.Private.CoreLib.dll" -out "/Users/mdhwang/runtime_wasm_clean/artifacts/obj/System.Reflection.Emit.Tests/net6.0-Release/browser-wasm/linked/" --nowarn ";SYSLIB0011;1701;1702;1705;1591;NU5105;1701;1702;IL2026;IL2041;IL2042;IL2043;IL2056;IL2045;IL2046;IL2050;IL2032;IL2055;IL2057;IL2058;IL2059;IL2060;IL2061;IL2096;IL2062;IL2063;IL2064;IL2065;IL2066;IL2067;IL2068;IL2069;IL2070;IL2071;IL2072;IL2073;IL2074;IL2075;IL2076;IL2077;IL2078;IL2079;IL2080;IL2081;IL2082;IL2083;IL2084;IL2085;IL2086;IL2087;IL2088;IL2089;IL2090;IL2091;IL2092;IL2093;IL2094;IL2095;IL2097;IL2098;IL2099;IL2008;IL2009;IL2037;IL2009;IL2012" --warn "5" --warnaserror --warnaserror ";NU1605" -b -c copyused -u copyused --skip-unresolved true
```
More readable form: [linker_failure_command.txt](https://github.com/mono/linker/files/5654931/linker_failure_command.txt)

**Comment by vitek-karas** [comment]
#1679 has the fix for this.

Just out of curiosity: trimming unit tests is typically not very helpful - it doesn't really test if the code will work when used in a trimmed app. This is mostly because unit tests (if done right) should cover pretty much all of the functionality and thus almost nothing should be trimmed. What is the scenario where trimming unit tests will be helpful?

**Comment by akoeplinger** [comment]
@vitek-karas this is for the scenario where e.g. we're testing System.Collections.Concurrent.Tests for wasm/iOS but the published app still gets dozens of large assemblies like System.Private.Xml.dll without trimming even though they're not needed by the test.

Once AOT is turned on this also explodes the time to compile the app bundle if we need to AOT the whole BCL.

**Comment by marek-safar** [comment]
Yep, the scenario is that we trim everything except the test itself and we expect problems with test dependencies which linker cannot track.
