### ISSUE TITLE
Linker crash in MarkType in release/5.0

### ISSUE THREAD

**Issue by agocke** [mono/linker#1677]
In `release/5.0`

```
ILLink: error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
Fatal error in IL Linker
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Internal error: unsupported type dependency TypeInAssembly')
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1387
   at Mono.Linker.Steps.MarkStep.ProcessModule(AssemblyDefinition assembly) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1163
   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1134
   at Mono.Linker.Steps.MarkStep.ResolveAssembly(IMetadataScope scope) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 2321
   at Mono.Linker.Steps.MarkStep.IgnoreScope(IMetadataScope scope) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1340
   at Mono.Linker.Steps.MarkStep.IsVirtualNeededByInstantiatedTypeDueToPreservedScope(MethodDefinition method) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1920
   at Mono.Linker.Steps.MarkStep.GetRequiredMethodsForInstantiatedType(TypeDefinition type)+MoveNext() in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 2488
   at Mono.Linker.Steps.MarkStep.MarkRequirementsForInstantiatedTypes(TypeDefinition type) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 2470
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1493
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1442
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1442
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1442
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1442
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1442
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1291
   at Mono.Linker.Steps.MarkStep.MarkEntireTypeInternal(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember, HashSet`1 typesAlreadyVisited) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 309
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, Boolean includeBaseTypes, DependencyInfo& reason, IMemberDefinition sourceLocationMember) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 273
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 1154
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 198
   at Mono.Linker.Steps.MarkStep.Initialize() in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 188
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context) in C:\Users\andy\Code\linker\src\linker\Linker.Steps\MarkStep.cs:line 180
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) in C:\Users\andy\Code\linker\src\linker\Linker\Pipeline.cs:line 135
   at Mono.Linker.Pipeline.Process(LinkContext context) in C:\Users\andy\Code\linker\src\linker\Linker\Pipeline.cs:line 128
   at Mono.Linker.Driver.Run(ILogger customLogger) in C:\Users\andy\Code\linker\src\linker\Linker\Driver.cs:line 755
   at Mono.Linker.Driver.Main(String[] args) in C:\Users\andy\Code\linker\src\linker\Linker\Driver.cs:line 64
```

**Comment by sbomer** [comment]
This looks like the issue that @mateoatr fixed in https://github.com/mono/linker/pull/1575 - are you using older bits?

**Comment by agocke** [comment]
Woops, forgot to mention, this is in the 5.0 release branch

**Comment by agocke** [comment]
Cherry-picking #1575 back fixes the issue. I think we should take this for servicing

**Comment by agocke** [comment]
@marek-safar Any objection to backporting this fix?

**Comment by sbomer** [comment]
The exception should only be thrown from debug bits. Did you hit it with the official bits?
https://github.com/mono/linker/blob/c68434193ec938e1f7f2360107c95007d7c831ee/src/linker/Linker.Steps/MarkStep.cs#L1408-L1411

**Comment by agocke** [comment]
No, local build, I'll try a release build

**Comment by agocke** [comment]
Release build works -- backporting may be unnecessary

**Comment by marek-safar** [comment]
This is debug build issue only. I don't think this will be approved by tactics as necessary for servicing

**Comment by agocke** [comment]
Agreed.
