### ISSUE TITLE
Unhandled exception on linked app

### ISSUE THREAD

**Issue by JustArchi** [mono/linker#168]
I'm using ILLink.Tasks in version 0.1.4-preview-981901.

During runtime of my linked app I've stumbled upon the following issue:

```
2017-10-23 13:19:33|ArchiSteamFarm-9808|FATAL|ASF|OnUnhandledException() System.ArgumentNullException: Value cannot be null.
Parameter name: method
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at System.Runtime.CompilerServices.CallSite`1.CreateCustomNoMatchDelegate(MethodInfo invoke)
   at System.Runtime.CompilerServices.CallSite`1.MakeUpdateDelegate()
   at System.Runtime.CompilerServices.CallSite`1.GetUpdateDelegate(T& addr)
   at System.Runtime.CompilerServices.CallSite`1.Create(CallSiteBinder binder)
   at ArchiSteamFarm.ArchiWebHandler.<GetServerTime>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.MobileAuthenticator.<GetSteamTime>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.MobileAuthenticator.<GenerateToken>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.Bot.<OnConnected>d__141.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

I suspect this is because `GetServerTime()` uses `dynamic` field inside, therefore reflection. Could you help me with creating appropriate `linker.xml` for this case? I've tried to use `<LinkerRootAssemblies Include="System.Runtime" />` but without luck. I'd appreciate a helpful hand, thank you in advance 👍.

**Comment by russellhadley** [comment]
@sbomer can you help here?

**Comment by erozenfeld** [comment]
The following xml file should help with this:
```
<linker>
    <assembly fullname="System.Linq.Expressions">
         <type fullname="System.Runtime.CompilerServices.CallSiteOps" required="true" />
    </assembly>
</linker>

```

**Comment by erozenfeld** [comment]
Actually, there was some refactoring in corefx that affected System.Runtime.CompilerServices.CallSiteOps. Depending on what version you have, you may need this instead:

```
<linker>
    <assembly fullname="System.Dynamic.Runtime">
         <type fullname="System.Runtime.CompilerServices.CallSiteOps" required="true" />
    </assembly>
</linker>
```

**Comment by JustArchi** [comment]
I tried both and `System.Linq.Expressions` one did the trick, thank you a lot! Sorry for forgetting that one misc detail - I'm targetting `netcoreapp2.0`.

Moving forward, I got the new unhandled exception 🙂.

```
2017-10-26 21:46:38|ArchiSteamFarm-7068|FATAL|ASF|OnUnhandledException() System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Dynamic.DynamicObject.MetaDynamic.IsOverridden(MethodInfo method)
   at System.Dynamic.DynamicObject.MetaDynamic.BindConvert(ConvertBinder binder)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at CallSite.Target(Closure , CallSite , Object )
   at ArchiSteamFarm.ArchiWebHandler.<GetServerTime>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.MobileAuthenticator.<GetSteamTime>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.MobileAuthenticator.<GenerateToken>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ArchiSteamFarm.Bot.<OnConnected>d__141.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

Any clue about this one? I honestly tried to learn from your example and write this one on my own but I guess I'm still not experienced with this enough yet to fully understand it 😞. Thank you in advance! 👍.

**Comment by erozenfeld** [comment]
Try this:
```
<linker>
    <assembly fullname="System.Linq.Expressions">
         <type fullname="System.Runtime.CompilerServices.CallSiteOps" required="true" />
         <type fullname="System.Dynamic.DynamicObject" required="true" />
    </assembly>
</linker>
```

**Comment by JustArchi** [comment]
Thank you a lot! That one indeed worked, one step closer to the victory 😀.

```
System.ArgumentNullException: Value cannot be null.
Parameter name: property
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Runtime.CompilerServices.CallSiteBinder.Stitch[T](Expression binding, LambdaSignature`1 signature)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at CallSite.Target(Closure , CallSite , Object )
   at ArchiSteamFarm.ArchiWebHandler.<GetServerTime>d__39.MoveNext()
```

Any tip on this one? I tried to add `System.Runtime.CompilerServices.CallSiteBinder` type to `System.Linq.Expressions` assembly but without luck. I think this is one of the last ones to patch 🙂. Thank you for support!

**Comment by erozenfeld** [comment]
Try this:
```
<linker>
    <assembly fullname="System.Linq.Expressions">
         <type fullname="System.Runtime.CompilerServices.CallSiteOps" required="true" />
         <type fullname="System.Dynamic.DynamicObject" required="true" />
    </assembly>

    <assembly fullname="System.Dynamic.Runtime">
        <type fullname="System.Runtime.CompilerServices.CallSite`1" required="true" />
    </assembly> 
</linker>
```

**Comment by JustArchi** [comment]
You're a magician, I don't know how to thank you, that one indeed the last one. Thanks for everything!

On a side note, those cases seem pretty generic to me, maybe they could be in some way added to monolinker and handled automatically? I'm not an expert here (as you probably noticed), so this is just a random thought based on entires alone.

In any case, app works flawlessly now, lots of thanks! 💓

**Comment by erozenfeld** [comment]
Thank you for the feedback. Yes, we may be able to do something to handle these cases automatically.
