### ISSUE TITLE
Null-reference exception in Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall

### ISSUE THREAD

**Issue by ramondeklein** [mono/linker#1741]
I use the [Z.EntityFramework.Plus.EFCore](https://www.nuget.org/packages/Z.EntityFramework.Plus.EFCore/5.1.11) library and it works great with .NET Core 5, but when I use it in my ready-to-run ARM executable, then the following error is shown:
```
ILLink : error IL1005: Z.Expressions.CodeCompiler.CSharp.ExpressionScope.(String,Type&): Error processing method 'Z.Expressions.CodeCompiler.CSharp.ExpressionScope.(String,Type&)' in assembly 'Z.Expressions.Eval.dll' [/builds/xxx.csproj]
  Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: Z.Expressions.CodeCompiler.CSharp.ExpressionScope.(String,Type&): Error processing method 'Z.Expressions.CodeCompiler.CSharp.ExpressionScope.(String,Type&)' in assembly 'Z.Expressions.Eval.dll'
   ---> System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.HandleCall(MethodBody callingMethodBody, MethodReference calledMethod, Instruction operation, ValueNodeList methodParams, ValueNode& methodReturnValue)
     at Mono.Linker.Dataflow.MethodBodyScanner.HandleCall(MethodBody callingMethodBody, Instruction operation, Stack`1 currentStack)
     at Mono.Linker.Dataflow.MethodBodyScanner.Scan(MethodBody methodBody)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ScanAndProcessReturnValue(MethodBody methodBody)
     at Mono.Linker.Steps.MarkStep.MarkReflectionLikeDependencies(MethodBody body, Boolean requiresReflectionMethodBodyScanner)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.MarkStep.ProcessQueue()
     at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
     at Mono.Linker.Steps.MarkStep.Process()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
```

**Comment by marek-safar** [comment]
This looks like some obfuscated code.

/cc @vitek-karas

**Comment by ramondeklein** [comment]
That could be correct, because I don't think this library is open-source. I use another approach now, so I could get rid of this (proprietary) library, but it might other code too.
