### ISSUE TITLE
TrimmerRootAssembly broken in recent SDKs

### ISSUE THREAD

**Issue by sbomer** [mono/linker#1772]
Linking a project with TrimmerRootAssembly crashes the linker (using SDK 6.0.100-alpha.1.21071.6)
```xml
  <ItemGroup>
    <TrimmerRootAssembly Include="System.Runtime" />
  </ItemGroup>
```
```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [/Users/sven/tmp/trimroot/trimroot.csproj]
         Fatal error in IL Linker
         Unhandled exception. System.IO.FileNotFoundException: Could not find file '/Users/sven/tmp/trimroot/System.Runtime'.
         File name: '/Users/sven/tmp/trimroot/System.Runtime'
            at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
            at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
            at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
            at Mono.Linker.DirectoryAssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
            at Mono.Linker.Steps.RootAssemblyInput.LoadAssemblyFile()
            at Mono.Linker.Steps.RootAssemblyInput.Process()
            at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Main(String[] args)
```

This looks like it was introduced by https://github.com/mono/linker/pull/1725 @marek-safar

**Comment by tlakollo** [comment]
This is causing the Xamarin .net 6 samples to fail, the default command line passes `-a "HelloAndroid" -a "obj\Debug\net6.0-android\HelloAndroid.dll"` to later on fail
```Fatal error in IL Linker
         Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Repos\TrimXamarin\net6repo\net6-samples\HelloAndroid\HelloAndroid'.
         File name: 'C:\Repos\TrimXamarin\net6repo\net6-samples\HelloAndroid\HelloAndroid'
            at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
            at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
            at Mono.Linker.DirectoryAssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
            at Mono.Linker.Steps.RootAssemblyInput.LoadAssemblyFile()
            at Mono.Linker.Steps.RootAssemblyInput.Process()
            at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Main(String[] args)```

**Comment by marek-safar** [comment]
Please update Android SDK it was fixed not to pass duplicated root inputs

**Comment by SupinePandora43** [comment]
net6 `6.0.100-preview.1.21103.13`
```
> dotnet publish -c Debug
Microsoft (R) Build Engine версии 16.9.0-preview-21103-02+198f3f262 для .NET
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Определение проектов для восстановления...
  Все проекты обновлены для восстановления.
  Вы используете предварительную версию .NET. Дополнительные сведения см. на странице https://aka.ms/dotnet-core-preview.
C:\Repos\net6-mobile-samples\HelloAndroid\MainActivity.cs(270,25): warning CS0169: Поле "MainActivity.factory" никогда не используется. [C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj]
C:\Repos\net6-mobile-samples\HelloAndroid\MainActivity.cs(206,39): warning CS0067: Событие "AndroidApplicationWindow.KeyPressed" никогда не используется. [C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj]
  HelloAndroid -> C:\Repos\net6-mobile-samples\HelloAndroid\bin\Debug\net6.0-android\HelloAndroid.dll
```
```
> dotnet publish -c Release
Microsoft (R) Build Engine версии 16.9.0-preview-21103-02+198f3f262 для .NET
(C) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

  Определение проектов для восстановления...
  Восстановлен C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj (за 2.22 sec).
  Вы используете предварительную версию .NET. Дополнительные сведения см. на странице https://aka.ms/dotnet-core-preview.
C:\Repos\net6-mobile-samples\HelloAndroid\MainActivity.cs(270,25): warning CS0169: Поле "MainActivity.factory" никогда не используется. [C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj]
C:\Repos\net6-mobile-samples\HelloAndroid\MainActivity.cs(206,39): warning CS0067: Событие "AndroidApplicationWindow.KeyPressed" никогда не используется. [C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj]
  HelloAndroid -> C:\Repos\net6-mobile-samples\HelloAndroid\bin\Release\net6.0-android\HelloAndroid.dll
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj]
  Fatal error in IL Linker
  Unhandled exception. Mono.Linker.InternalErrorException: Step 'LoadReferencesStep' failed when processing assembly 'HelloAndroid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1010: Assembly 'HelloAndroid, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' cannot be loaded due to failure in processing 'Veldrid, Version=4.8.0.0, Culture=neutral, PublicKeyToken=null' reference
   ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1010: Assembly 'Veldrid, Version=4.8.0.0, Culture=neutral, PublicKeyToken=null' cannot be loaded due to failure in processing 'SharpDX.Direct3D11, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' reference
   ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1010: Assembly 'SharpDX.Direct3D11, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' cannot be loaded due to failure in processing 'SharpDX, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' reference
   ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1010: Assembly 'SharpDX, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1' cannot be loaded due to failure in processing 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference
   ---> Mono.Linker.LinkerFatalErrorException: ILLink: error IL1009: Assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' reference 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' could not be resolved
   ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   ---> System.IO.FileNotFoundException: Unable to find 'System.Security.Permissions.dll' or 'System.Security.Permissions.exe' file
     at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
     at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
     --- End of inner exception stack trace ---
     at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
     at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     --- End of inner exception stack trace ---
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Выполняется оптимизация сборок по размеру, что может изменить поведение приложения. Обязательно проведите тестирование после публикации. Дополнительные сведения см. на странице https://aka.ms/dotnet-illink.
C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(51,5): error NETSDK1144: не удалось оптимизировать сборки под размер. Оптимизацию можно отключить, установив значение false для свойства PublishTrimmed. [C:\Repos\net6-mobile-samples\HelloAndroid\HelloAndroid.csproj]
```

# Workaround
## CLI
`-p:PublishTrimmed=false`
## csproj
```xml
<PublishTrimmed>false</PublishTrimmed>
```
