### ISSUE TITLE
SZArrayHelper.get_Count System.NotSupportedException: Linked away

### ISSUE THREAD

**Issue by eerhardt** [mono/linker#1832]
`dotnet publish -p:PublishTrimmed=true -p:TrimMode=link -r win-x64` the following application with the latest `mono/linker`:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
  </ItemGroup>
</Project>
```

```C#
using System;
using System.Collections.Generic;
using System.Drawing;
using Newtonsoft.Json;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var data = @"{""name"":""Test"",""sizes"":[{""id"":0,""tileSize"":""256, 256""}],""colors"":[{""id"":0,""color"":""51, 136, 255""}]}";

            var s = JsonConvert.DeserializeObject<Shape>(data);
            Console.WriteLine(s.Sizes[0].TileSize);
        }
    }

    public class Shape
    {
        public string Name { get; set; }

        public List<Sizelayer> Sizes { get; set; }

        public List<ColorLayer> Colors { get; set; }
    }

    public class Sizelayer
    {
        public int Id { get; set; }

        public Size TileSize { get; set; } = new Size(256, 256);
    }

    public class ColorLayer
    {
        public int Id { get; set; }

        public Color Color { get; set; } = Color.FromArgb(0x33, 0x88, 0xFF);
    }
}
```

Run the app:

```
> .\bin\Debug\net5.0\win-x64\publish\ConsoleApp1.exe
Unhandled exception. System.NotSupportedException: Linked away
   at System.SZArrayHelper.get_Count[T]()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes(Object attributeProvider, Type attributeType, Boolean inherit)
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes[T](Object attributeProvider, Boolean inherit)
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttribute[T](Object attributeProvider, Boolean inherit)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute[T](Type type)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute[T](Object provider)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.CachedAttributeGetter`1.GetAttribute(Object type)
   at Newtonsoft.Json.Serialization.JsonTypeReflector.GetCachedAttribute[T](Object attributeProvider)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at ConsoleApp1.Program.Main(String[] args) in C:\temp\ConsoleApp1\Program.cs:line 14
```

This looks like https://github.com/mono/linker/issues/1398, but that was fixed in `5.0`, so I'm not sure why this is cropping up again.

**Comment by MichalStrehovsky** [comment]
Looks like a bad interaction of #1799. https://github.com/dotnet/runtime/pull/47632 should have covered it, but from the exception it looks like illink still doesn't think the type gets instantiated. Maybe it's good we didn't go with my suggestion in https://github.com/dotnet/runtime/pull/47632#pullrequestreview-579379124 because that would probably have papered over it.

**Comment by marek-safar** [comment]
Hmm, this is because you are using 6.0 linker with 5.0 libraries. We could turn off the new optimizations when targetting 5.0 or backport the fix (or both). Backporting the fix would make sense anyway because someone can enable the optimization even with 5.0 linker.

**Comment by eerhardt** [comment]
> Hmm, this is because you are using 6.0 linker with 5.0 libraries.

Note that this is a supported scenario. We should probably be testing it. When users install a new SDK, that new SDK is used even when they are targeting older TFMs.
