### ISSUE TITLE
Failed to resolve System.Int32 SQLitePCL.ISQLite3Provider::sqlite3_blob_open

### ISSUE THREAD

**Issue by jeromelaban** [mono/linker#1919]
When building a .NET wasm app with a reference to `SQLitePCLRaw.provider.sqlite3`, the following error happens:

```
Mono.Linker.LinkerFatalErrorException: ILLink: error IL1005: SQLitePCL.SQLite3Provider_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_blob_open(sqlite3,utf8z,utf8z,utf8z,Int64,Int32,sqlite3_blob&): Error processing method 'SQLitePCL.SQLite3Provider_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_blob_open(sqlite3,utf8z,utf8z,utf8z,Int64,Int32,sqlite3_blob&)' in assembly 'SQLitePCLRaw.provider.sqlite3.dll'
 ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 SQLitePCL.ISQLite3Provider::sqlite3_blob_open(SQLitePCL.sqlite3,SQLitePCL.utf8z,SQLitePCL.utf8z,SQLitePCL.utf8z,System.Int64,System.Int32,SQLitePCL.sqlite3_blob&)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference) in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 3221
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason, Nullable`1 origin) in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 2556
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason) in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 2701
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 500
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue() in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 502
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue() in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 424
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context) in /__w/1/s/linker/src/linker/Linker.Steps/MarkStep.cs:line 197
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step) in /__w/1/s/linker/src/linker/Linker/Pipeline.cs:line 166
   at Mono.Linker.Pipeline.Process(LinkContext context) in /__w/1/s/linker/src/linker/Linker/Pipeline.cs:line 159
   at Mono.Linker.Driver.Run(ILogger customLogger) in /__w/1/s/linker/src/linker/Linker/Driver.cs:line 701
```

This error only happens if:

```xml
<linker>
	<assembly fullname="SQLitePCLRaw.provider.sqlite3" />
</linker>
```

If the assembly is not in the linker configuration file, at runtime, the following happens:

```
System.TypeLoadException: VTable setup of type SQLitePCL.SQLite3Provider_sqlite3 failed
monoeg_g_printerr    @    00e2b396:0x2574c
mono_print_unhandled_exception_internal    @    00e2b396:0xfba0f
mono_unhandled_exception_checked    @    00e2b396:0x1b2073
mono_unhandled_exception_internal    @    00e2b396:0xa637d
mono_handle_exception_internal    @    00e2b396:0x101559
mono_handle_exception    @    00e2b396:0x101ca5
interp_throw    @    00e2b396:0x6f8b
interp_exec_method    @    00e2b396:0x82907
interp_runtime_invoke    @    00e2b396:0x1db87a
```

Repro: https://github.com/jeromelaban/Wasm.Samples/tree/master/LinkerBug1919

**Comment by vitek-karas** [comment]
This is a change in `SQLitePCL`. Linker is given these two assemblies:
* `SQLitePCLRaw.core, 2.0.5.1114`
* `SQLitePCLRaw.provider.sqlite3, 2.0.4.976`

The `provider` implements the method `sqlite3_blob_open` on an interface declared in the `core`.
The provider's implementation has the method with last parameter declared as `sqlite_blob_3`.
The code's interface declaration has the method with last parameter declared as `IntPtr`.

This seems like a version mismatch. If I get `SQLitePCLRaw.provider.sqlite3, 2.0.5.1114` that has the implementation of the right method.

I don't see how this is a linker issue - the SDK/Build in this case somehow resolved incompatible dependencies.

**Comment by jeromelaban** [comment]
Indeed that's the issue, upgrading fixes it and it's not a linker issue. The interesting part here is that nuget probably should have reported the package downgrade but did not...

Thanks for the investigation!

**Comment by vitek-karas** [comment]
I think it only saw package upgrade - the `provider` version 2.0.4 asked for `core` version 2.0.4, but something else asked for `core` 2.0.5 - and so it was just an upgrade. I honestly don't know how this is supposed to work in NuGet.
