### ISSUE TITLE
Error when trying to trim an ASP.NET Core project

### ISSUE THREAD

**Issue by davidfowl** [mono/linker#2211]
Project:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishTrimmed>true</PublishTrimmed>
  </PropertyGroup>

</Project>
```

Program.cs

```C#
var builder = WebApplication.CreateBuilder(args);
var app = builder.Build();

app.MapGet("/", () => "Hello World!");

app.Run();
```

Command:

dotnet publish -r win-x64

Exception:

```
ILLink : error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues [C:\Users\david\source\repos\WebApplication520\WebApplication3\WebApplication3.csproj]
  Fatal error in IL Linker
  Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
     at Mono.Linker.MessageContainer.TryLogSingleWarning(LinkContext context, Int32 code, MessageOrigin origin, String subcategory)
     at Mono.Linker.MessageContainer.CreateWarningMessageContainer(LinkContext context, String text, Int32 code, MessageOrigin origin, WarnVersion version, String subcategory)
     at Mono.Linker.MessageContainer.CreateWarningMessage(LinkContext context, String text, Int32 code, MessageOrigin origin, WarnVersion version, String subcategory)
     at Mono.Linker.LinkContext.LogWarning(String text, Int32 code, MessageOrigin origin, String subcategory)
     at Mono.Linker.Steps.MarkStep.ReportRequiresUnreferencedCode(String displayName, RequiresUnreferencedCodeAttribute requiresUnreferencedCode, MessageOrigin currentOrigin)
     at Mono.Linker.Steps.MarkStep.CheckAndReportRequiresUnreferencedCode(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessAnalysisAnnotationsForMethod(MethodDefinition method, DependencyKind dependencyKind)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkIndirectlyCalledMethod(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkMethodVisibleToReflection(MethodDefinition method, DependencyInfo& reason)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.<>c__DisplayClass35_0.<MarkMethod>b__0()
     at Mono.Linker.Dataflow.ReflectionPatternContext.RecordRecognizedPattern(IMetadataTokenProvider accessedItem, Action mark)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.MarkMethod(ReflectionPatternContext& reflectionContext, MethodDefinition method, DependencyKind dependencyKind)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.MarkTypeForDynamicallyAccessedMembers(ReflectionPatternContext& reflectionContext, TypeDefinition typeDefinition, DynamicallyAccessedMemberTypes requiredMemberTypes, DependencyKind dependencyKind, Boolean declaredOnly)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.RequireDynamicallyAccessedMembers(ReflectionPatternContext& reflectionContext, DynamicallyAccessedMemberTypes requiredMemberTypes, ValueNode value, IMetadataTokenProvider targetContext)
     at Mono.Linker.Dataflow.ReflectionMethodBodyScanner.ProcessAttributeDataflow(MethodDefinition method, IList`1 arguments)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributeArguments(CustomAttribute ca)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkModule(ModuleDefinition module, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
     at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
     at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
     at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
  Optimizing assemblies for size, which may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
C:\Program Files\dotnet\sdk\6.0.100-rc.1.21411.31\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets(108,5): error NETSDK1144: Optimizing assemblies for size failed. Optimization can be disabled by setting the PublishTrimmed property to false. [C:\Users\david\source\repos\WebApplication520\WebApplication3\WebApplication3.csproj]
```

SDK version: 6.0.100-rc.1.21411.31

**Comment by davidfowl** [comment]
Is this going to make it into rc1?

**Comment by sbomer** [comment]
That's the plan: https://github.com/mono/linker/pull/2220
