### ISSUE TITLE
.net 5 blazor webassembly project trying to update to .net 6 rc 1 and AOT  

### ISSUE THREAD

**Issue by dkboon01** [mono/linker#2310]
I have a blazor webassemly project - the base project ABCBlazor is wasm , 2nd project is a razor component library and 3rd project is a dll that is built on .net standard 2.0.   Should I be able to convert my razor component library and my blazor wasm project to dotnet 6 and use AOT when publishing ?  Here is the error I receive.   Please help we are trying to improve on the speed of our application

ILLink(0,0): Error IL1012: IL Linker has encountered an unexpected error. Please report the issue at https://github.com/mono/linker/issues
Fatal error in IL Linker
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Linker.CustomAttributeSource.HasAny(ICustomAttributeProvider provider)
   at Mono.Linker.AnnotationStore.GetLinkerAttributes[T](IMemberDefinition member)
   at Mono.Linker.AnnotationStore.TryGetLinkerAttribute[T](IMemberDefinition member, T& attribute)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
   at Mono.Linker.Steps.MarkStep.MarkModule(ModuleDefinition module, DependencyInfo reason)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
   at Mono.Linker.Steps.MarkStep.MarkGenericArguments(IGenericInstance instance)
   at Mono.Linker.Steps.MarkStep.GetOriginalType(TypeReference type, DependencyInfo reason)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference, DependencyInfo reason, Nullable`1 origin)
   at Mono.Linker.Steps.MarkStep.MarkField(FieldDefinition field, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireType(TypeDefinition type, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.MarkEntireAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly, DependencyInfo reason)
   at Mono.Linker.Steps.MarkStep.ProcessMarkedPending()
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)

here is the .csproj for blazor wasm <Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <RunAOTCompliation>true</RunAOTCompliation>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="BlazorDownloadFile" Version="2.1.6" />
    <PackageReference Include="BlazorGoogleMaps" Version="1.1.8" />
    <PackageReference Include="ES.CommonServices" Version="1.0.122" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="6.0.0-rc.1.21452.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="6.0.0-rc.1.21452.15" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Authentication.WebAssembly.Msal" Version="6.0.0-rc.1.21452.15" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="4.0.0-preview2.21264.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0-rc.1.21451.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="2.27.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ABCDispatchComponents\ABCDispatchComponents.csproj">
      <TreatAsUsed>true</TreatAsUsed>
    </ProjectReference>
    <ProjectReference Include="..\ABCServices\ABCServices.csproj" />
  </ItemGroup>

</Project>

**Comment by dkboon01** [comment]
So what is the solution for this problem?
