### ISSUE TITLE
" Too many open files" in ModuleDefinition.ReadModule

### ISSUE THREAD

**Issue by danmosemsft** [mono/linker#284]
We got this reported one-off in building .NET CoreFX for Mac. May not be actionable - but here you are in case. Perhaps a dispose is missing on some FileStream, so it's possible for too many to get opened at once.
```
On Mac, Build.sh –Release failed, please see below output. Please give some suggestion for this if you can.
Fatal error in IL Linker
System.IO.IOException: Too many open files
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Mono.Linker.DirectoryAssemblyResolver.GetAssembly(String file, ReaderParameters parameters)
   at Mono.Linker.DirectoryAssemblyResolver.SearchDirectory(AssemblyNameReference name, IEnumerable`1 directories, ReaderParameters parameters)
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name)
   at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
   at Mono.Linker.TypeReferenceExtensions.<GetMethods>d__4.MoveNext()
   at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(TypeDefinition type, MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.GetBaseMethodInTypeHierarchy(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualBaseMethod(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethod(MethodDefinition method)
   at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
   at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run()
   at Mono.Linker.Driver.Main(String[] args)
```

@erozenfeld

**Comment by marek-safar** [comment]
This looks like an issue somewhere else and we are hitting the open files limit just here as `ModuleDefinition.ReadModule` closes the stream immediately
