### ISSUE TITLE
Fatal error in IL Linker with same build output

### ISSUE THREAD

**Issue by JustArchi** [mono/linker#285]
```
Fatal error in IL Linker
System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Cecil.MetadataBuilder.GetExportedTypeScope(ExportedType exported_type)
   at Mono.Cecil.MetadataBuilder.AddExportedTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory, WriterParameters writerParameters)
   at Mono.Linker.Steps.OutputStep.WriteAssembly(AssemblyDefinition assembly, String directory)
   at Mono.Linker.Steps.OutputStep.OutputAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.OutputStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

I reproduced it by calling `dotnet build -c Release -o out` with `ILLink.Tasks 0.1.5-preview-1461378` **twice** to the same directory. Normally second build would just update the directory with new content, and therefore it's entirely valid, but mono linker seems to have some difficulties with that.

This issue is not reproducible if you manually remove `out` directory before calling `dotnet build` for the second time. I reproduced this one on Windows and had no luck doing the same on Linux.

Thank you in advance.

```
C:\Users\Archi>dotnet --info
Narzędzia wiersza polecenia programu .NET (2.1.100)

Product Information:
 Version:            2.1.100
 Commit SHA-1 hash:  b9e74c6520

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.100\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54
```

**Comment by marek-safar** [comment]
Although this looks like cecil issue

**Comment by marek-safar** [comment]
Do you still have the repro app which is failing with this error?

**Comment by JustArchi** [comment]
Sorry, I'm not able to reproduce this anymore with recent tooling, I believe this issue can be closed. Thanks for your interest.
