### ISSUE TITLE
Fatal error in IL Linker with latest SDK

### ISSUE THREAD

**Issue by JustArchi** [mono/linker#286]
```
ILLINK : warning : unresolved assembly System.Runtime [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Threading.Tasks [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Collections [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Runtime.Extensions [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Diagnostics.Debug [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Threading [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Xml.ReaderWriter [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Linq.Expressions [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Collections.Concurrent [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Threading.Timer [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.IO.FileSystem.Watcher [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.IO.Compression [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Collections.Specialized [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Security.Cryptography.Csp [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Text.RegularExpressions [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Linq [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Security.Cryptography.Algorithms [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Net.WebSockets [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Net.Primitives [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Net.HttpListener [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Diagnostics.Process [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Net.WebSockets.Client [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Resources.ResourceManager [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Console [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Net.Http [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Diagnostics.Tools [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.IO.FileSystem [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.IO.Compression.ZipFile [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Security.Cryptography.Primitives [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Linq.Parallel [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Runtime.InteropServices.RuntimeInformation [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Runtime.InteropServices [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.Net.ServicePoint [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly Microsoft.CSharp [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
ILLINK : warning : unresolved assembly System.ComponentModel.TypeConverter [/home/archi/ArchiSteamFarm/ArchiSteamFarm/ArchiSteamFarm.csproj]
Fatal error in IL Linker
Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified> ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessReferences(AssemblyDefinition assembly, LinkContext context)
   at Mono.Linker.Steps.ResolveFromXmlStep.GetAssembly(LinkContext context, AssemblyNameReference assemblyName)
   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
   at Mono.Linker.Steps.ResolveFromXmlStep.Process()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.ResolveFromXmlStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

The same project compiled exactly the same under `2.1.3` SDK works fine.

Thank you in advance.

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300-preview2-008375
 Commit:    04ba0c9523

Runtime Environment:
 OS Name:     debian
 OS Version:
 OS Platform: Linux
 RID:         debian-x64
 Base Path:   /opt/dotnet/sdk/2.1.300-preview2-008375/

Host (useful for support):
  Version: 2.1.0-preview2-26313-01
  Commit:  3c802455b2

.NET Core SDKs installed:
  2.1.300-preview2-008375 [/opt/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0-preview2-30338 [/opt/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0-preview2-30338 [/opt/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.0-preview2-26313-01 [/opt/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by sbomer** [comment]
@JustArchi, thanks for reporting this!
I spent some time digging into this, and I believe I understand the issue. It looks like this has to do with the use of [ResolvePackageAssets](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageAssets.cs) in newer versions of the SDK instead of [ResolvePackageDependencies](https://github.com/dotnet/sdk/blob/master/src/Tasks/Microsoft.NET.Build.Tasks/ResolvePackageDependencies.cs), a change made in https://github.com/dotnet/sdk/pull/1857. The ResolvedPath metadata, which we use [to get reference assembly paths](https://github.com/mono/linker/blob/39560549290237b27a196672d779519e61c5dd54/corebuild/integration/ILLink.Tasks/ILLink.Tasks.targets#L346), is no longer set on the output itemgroup. The result for us is that most reference assemblies aren't being passed to the linker, which also explains all of those warnings. I'm still looking into a fix.

**Comment by JustArchi** [comment]
No problem, I'm glad I could help by reporting the issue 🙂. I'll wait patiently for the fix and be happy to report back once it's merged, no need to hurry, thank you a lot for everything, I love this tool.

**Comment by JustArchi** [comment]
Side note, it looks like this problem affects only framework (as in, no `--runtime`) compilation, since self-contained apps are being linked normally, **[ref](https://ci.appveyor.com/project/JustArchi/archisteamfarm/build/5319-master/job/yg94ftc4jssdi9yh#L280)**.

**Comment by JustArchi** [comment]
This is now reproducible on official .NET Core 2.1 SDK when no `--runtime` is given.

**Comment by marek-safar** [comment]
Does the issue still happen with 3.0?

**Comment by JustArchi** [comment]
I'm no longer using 3.0 with ILLink.Tasks, and actually ILLink.Tasks is incompatible with 3.0, so I'm not sure how I'm supposed to answer.
