### ISSUE TITLE
Fails on Microsoft.CodeAnalysis.CSharp.Features

### ISSUE THREAD

**Issue by SteveSandersonMS** [mono/linker#369]
If you add the following to your project:

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Features" Version="2.9.0" />
```

... then the linker fails with the following error:

```
1>Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\username\.nuget\packages\microsof.codeanalysis.workspaces.common\2.9.0\lib\netstandard1.3\es\Microsoft.CodeAnalysis.Workspaces.resources.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\username\.nuget\packages\microsof.codeanalysis.workspaces.common\2.9.0\lib\netstandard1.3\es\Microsoft.CodeAnalysis.Workspaces.resources.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
1>   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
1>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
1>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
1>   at Mono.Linker.LinkContext.Resolve(String name)
1>   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
1>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

It looks like it incorrectly thinks the embedded resources are a reference to an external assembly, but they aren't.

**Comment by marek-safar** [comment]
Could you please provide self-contained repro?

**Comment by SteveSandersonMS** [comment]
Thanks @marek-safar for suggesting that, because after some investigation, I've tracked it down to an underlying issue that is not what first appeared. It comes down to a bug in MSBuild, so I'll close this issue and report a different one requesting a workaround for the MSBuild bug.
