### ISSUE TITLE
Fatal error in IL Linker

### ISSUE THREAD

**Issue by kentcb** [mono/linker#374]
I thought I'd try linking my netcoreapp2.1 AWS lambda package, but very quickly ran into the following issue:
```
ILLINK : warning : unresolved assembly System.Runtime [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Threading.Tasks [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Diagnostics.Debug [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Net.Primitives [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Collections.Immutable [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Runtime.Extensions [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Runtime.Serialization.Primitives [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Data.Common [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Collections [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Linq [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Threading [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly netstandard [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Threading.Tasks.Extensions [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Resources.ResourceManager [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Reflection [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Xml.ReaderWriter [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Runtime.Numerics [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.IO [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Globalization [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Text.Encoding [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Reflection.Extensions [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Security.Cryptography.Algorithms [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Security.Cryptography.Primitives [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.ObjectModel [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.IO.FileSystem [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Net.Http [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Net.Requests [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Xml.XDocument [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Threading.Timer [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Threading.Thread [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Text.RegularExpressions [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Text.Encoding.Extensions [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Reflection.TypeExtensions [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Runtime.InteropServices.RuntimeInformation [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Console [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.IO.FileSystem.Primitives [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
ILLINK : warning : unresolved assembly System.Runtime.InteropServices [C:\Users\kent\Repository\<<redacted>>.Services\Src\LambdaFunctions\LambdaFunctions.csproj]
Fatal error in IL Linker
Mono.Cecil.ResolutionException: Failed to resolve System.Security.Permissions.SecurityPermissionAttribute
   at Mono.Linker.Steps.MarkStep.MarkSecurityAttribute(SecurityAttribute sa)
   at Mono.Linker.Steps.MarkStep.MarkSecurityDeclaration(SecurityDeclaration sd)
   at Mono.Linker.Steps.MarkStep.MarkSecurityDeclarations(ISecurityDeclarationProvider provider)
   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

**Comment by kentcb** [comment]
@marek-safar Sorry to @ you, but I haven't had any movement on this issue. Is there anything more I need to provide?

**Comment by marek-safar** [comment]
This looks like something was missing in the msbuild pipeline processing as all references are missing. Please reopen if the issue persists in the latest versions
