### ISSUE TITLE
Fatal error in IL Linker during Mono.Linker.TypeReferenceExtensions.GetMethods

### ISSUE THREAD

**Issue by ericstj** [mono/linker#445]
https://dev.azure.com/dnceng/public/_build/results?buildId=75548&view=logs&jobId=05c104f8-fcb4-51be-f321-25b9d6e03ec7&taskId=a92d3a56-b430-5652-8fab-d4edc42f6ab6&lineStart=2285&lineEnd=2300&colStart=1&colEnd=99

```
2019-01-18T00:59:53.2367971Z Fatal error in IL Linker
2019-01-18T00:59:53.2565546Z System.InvalidOperatoinException: Operation is not valid due to the current state of the object.
2019-01-18T00:59:53.2566112Z    at Mono.Collections.Generic.Collection`1.Enumerator.CheckState()
2019-01-18T00:59:53.2566269Z    at Mono.Collections.Generic.Collection`1.Enumerator.MoveNext()
2019-01-18T00:59:53.2566430Z    at Mono.Linker.TypeReferenceExtensions.GetMethods(TypeReference type)+MoveNext()
2019-01-18T00:59:53.2566570Z    at Mono.Linker.Steps.TypeMapStep.TryMatchMethod(TypeReference type, MethodDefinition method)
2019-01-18T00:59:53.2569179Z    at Mono.Linker.Steps.TypeMapStep.GetBaseMethodsInInterfaceHierarchy(TypeReference type, MethodDefinition method)+MoveNext()
2019-01-18T00:59:53.2569344Z    at Mono.Linker.Steps.TypeMapStep.MapVirtualInterfaceMethod(MethodDefinition method)
2019-01-18T00:59:53.2569482Z    at Mono.Linker.Steps.TypeMapStep.MapVirtualMethod(MethodDefinition method)
2019-01-18T00:59:53.2570485Z    at Mono.Linker.Steps.TypeMapStep.MapVirtualMethods(TypeDefinition type)
2019-01-18T00:59:53.2570907Z    at Mono.Linker.Steps.TypeMapStep.MapType(TypeDefinition type)
2019-01-18T00:59:53.2571018Z    at Mono.Linker.Steps.TypeMapStep.ProcessAssembly(AssemblyDefinition assembly)
2019-01-18T00:59:53.2571142Z    at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
2019-01-18T00:59:53.2571284Z    at Mono.Linker.Pipeline.Process(LinkContext context)
2019-01-18T00:59:53.2571396Z    at Mono.Linker.Driver.Run(ILogger customLogger)
2019-01-18T00:59:53.2571616Z    at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

Same code succeeds on rebuild.  It appears that something is modifying the collection while enumerating it. https://github.com/mono/mono-basic/blob/e31cb702937a0adcc853250a0989c5f43565f9b8/vbnc/cecil/Mono.Collections.Generic/Collection.cs#L444

**Comment by ericstj** [comment]
Closing for now per https://github.com/dotnet/corefx/issues/30714#issuecomment-499945553
