### ISSUE TITLE
Fix failing .NET Core build (from new tests)

### ISSUE THREAD

**Issue by sbomer** [mono/linker#515]
Our builds are failing:
https://github.com/dotnet/core-eng/issues/5756

```
Failed   OnReferenceType.BaseProvidesInterfaceMember.GenericInterfaceWithMethodComplex2
Error Message:
   Custom attributes on `test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' are not matching
  Expected: equivalent to < "System.Diagnostics.DebuggableAttribute" >
  But was:  <empty>
  Missing (1): < "System.Diagnostics.DebuggableAttribute" >
 
Stack Trace:
   at Mono.Linker.Tests.TestCasesRunner.AssemblyChecker.VerifyCustomAttributes(ICustomAttributeProvider src, ICustomAttributeProvider linked) in /_/test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs:line 496
   at Mono.Linker.Tests.TestCasesRunner.AssemblyChecker.Verify() in /_/test/Mono.Linker.Tests/TestCasesRunner/AssemblyChecker.cs:line 31
   at Mono.Linker.Tests.TestCasesRunner.ResultChecker.Check(LinkedTestCaseResult linkResult) in /_/test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs:line 57
   at Mono.Linker.Tests.TestCases.All.Run(TestCase testCase) in /_/test/Mono.Linker.Tests/TestCases/TestSuites.cs:line 151
   at Mono.Linker.Tests.TestCases.All.InheritanceInterfaceTests(TestCase testCase) in /_/test/Mono.Linker.Tests/TestCases/TestSuites.cs:line 114
 ```

Looks like it happens after https://github.com/mono/linker/commit/327e73f0830ae6cfe377dbbc761ba6000a9ea934. I believe this should be as simple as removing `[assembly: KeptAttributeAttribute (typeof (System.Diagnostics.DebuggableAttribute))]` from the new tests, which were introduced in a PR from before the .NET Core bringup of unit tests.

**Comment by sbomer** [comment]
Oh - looks like @mrvoorhe is already doing this in https://github.com/mono/linker/pull/514/files. Thank you!
