### ISSUE TITLE
Fatal error in IL Linker. Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by karelz** [mono/linker#604]
_From @thangduo on Thursday, April 25, 2019 6:12:21 PM_

# Issue Title

I am getting a fatal error in IL Linker.

Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

# General

Using .NET Core 3.0 Preview SDK release for Mac to build a new Blazor hello world web application. The application uses System.ServiceModel.Http version="4.5.3" to communicate with another web application (similar to WCF).

The following was installed at /usr/local/share/dotnet 
.NET Core SDK 3.0.100-preview4-011223
.NET Core Runtime 3.0.0-preview4-27615-11
ASP.NET Core Runtime 3.0.0-preview4-19216-03

Error when running the `dotnet build` command:

```Batch
dotnet build
Microsoft (R) Build Engine version 16.1.54-preview+gd004974104 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
 
  Restore completed in 38.26 ms for <redacted path>/WebApplication1/WebApplication1.csproj.
/usr/local/share/dotnet/sdk/3.0.100-preview4-011223/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(151,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [<redacted path>/WebApplication1/WebApplication1.csproj]
  WebApplication1 -> <redacted path>/WebApplication1/bin/Debug/netstandard2.0/WebApplication1.dll
  Fatal error in IL Linker
  
  Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Private.ServiceModel, Version=4.5.0.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
     at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
     at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name)
     at Mono.Cecil.MetadataResolver.Resolve(TypeReference type)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(LinkContext context, AssemblyDefinition assembly, RootVisibility rootVisibility)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.ProcessLibrary(AssemblyDefinition assembly)
     at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

_Copied from original issue: dotnet/core#2637_

**Comment by karelz** [comment]
_From @arivoir on Saturday, May 11, 2019 6:56:55 PM_

Same problem here

**Comment by karelz** [comment]
_From @karelz on Friday, May 17, 2019 10:03:25 PM_

@sbomer can you please help me route the issue? Should it be moved to https://github.com/mono/linker?

**Comment by karelz** [comment]
_From @sbomer on Friday, May 17, 2019 10:29:59 PM_

Yes, could you please move it? I don't have permissions to use the GitHub issue move feature.

**Comment by marek-safar** [comment]
@sbomer this looks like some of the netcore path/reference issues

**Comment by sbomer** [comment]
This issue was filed before the reference path updates. I'm a little surprised that blazor is redistributing illink and running it during their build - I had no idea they were doing this. In any case, I tested with the latest preview and wasn't able to repro the issue. I believe this was an issue on their end as they are calling illink.dll directly and passing it directories for assembly resolution.
