### ISSUE TITLE
Add Assembly.Load (..) heuristic

### ISSUE THREAD

**Issue by sbomer** [mono/linker#652]
https://github.com/dotnet/coreclr/issues/25296#issue-458909111 from @ajaybhargavb

> **Repro:**
> - `mkdir MyApp`
> - `cd MyApp`
> - `dotnet new mvc`
> - Add the following to the `MyApp.csproj`
> ```xml
>     <OutputType>Exe</OutputType>
>     <PublishTrimmed>true</PublishTrimmed>
>     <PublishReadyToRun>true</PublishReadyToRun>
>     <PublishSingleFile>true</PublishSingleFile>
>     <RuntimeIdentifier>win-x64</RuntimeIdentifier>
> ```
> - `dotnet publish -c release` (There will be a bunch of warnings from `ReadyToRunCompiler`)
> - Go to the publish folder and open `MyApp.exe` 
> - Navigate to https://localhost:5001
> 
> **Expected:**
> App runs successfully
> 
> **Actual:**
> 500 - `System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`
> 
> **Workaround:**
> Set `PublishTrimmed` to `false`.
> 
> Note: This issue does not occur for console applications
> 
> <details>
> <summary>Dotnet Info</summary>
> 
> ```
> .NET Core SDK (reflecting any global.json):
>  Version:   3.0.100-preview6-012264
>  Commit:    be3f0c1a03
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18362
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\
> 
> Host (useful for support):
>   Version: 3.0.0-preview6-27804-01
>   Commit:  fdf81c6faf
> 
> .NET Core SDKs installed:
>   2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
>   2.2.300 [C:\Program Files\dotnet\sdk]
>   3.0.100-preview6-012264 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.0.0-preview6.19307.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> ```
> 
> </details>

https://github.com/dotnet/coreclr/issues/25296#issuecomment-505081283 from @sbomer 

> 
> @ajaybhargavb, could you try adding the following to your project?
> ```
> <ItemGroup>
>   <TrimmerRootAssembly Include="System.Threading.Tasks" />
> </ItemGroup>
> ```
> In general, we expect to see issues like this due to reflection, and are attempting to provide guidance at https://aka.ms/dotnet-illink - let me know if anything could be made clearer. Since this looks like it will be a very common case, we may be able to make this more automatic in the future (by shipping ASP.NET Core with some default roots, or similar).

https://github.com/dotnet/coreclr/issues/25296#issuecomment-505088449 from @ajaybhargavb
> @sbomer, I tried it but that still doesn't help. I get the same error.

https://github.com/dotnet/coreclr/issues/25296#issuecomment-505156154 from @sbomer 
> @ajaybhargavb adding that root assembly fixes the issue when I try it, using the same version of the SDK that you're using. Did you re-run the publish command after adding the root? Could you make sure your project file matches the following?
> ```xml
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>netcoreapp3.0</TargetFramework>
>     <OutputType>Exe</OutputType>
>     <PublishTrimmed>true</PublishTrimmed>
>     <PublishReadyToRun>true</PublishReadyToRun>
>     <PublishSingleFile>true</PublishSingleFile>
>     <RuntimeIdentifier>win-x64</RuntimeIdentifier>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <TrimmerRootAssembly Include="System.Threading.Tasks" />
>   </ItemGroup>
> 
> </Project>
> ```

https://github.com/dotnet/coreclr/issues/25296#issuecomment-505183539 from @ajaybhargavb
> 
> @sbomer you are right, it works. I must have messed something up when I tried it the other day. 
> 
> > In general, we expect to see issues like this due to reflection, and are attempting to provide guidance at https://aka.ms/dotnet-illink - let me know if anything could be made clearer. Since this looks like it will be a very common case, we may be able to make this more automatic in the future (by shipping ASP.NET Core with some default roots, or similar).
> 
> Yes, this looks to be a very common case. It happens in our web project templates.

**Comment by sbomer** [comment]
Call stack for future reference:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

File name: 'System.Threading.Tasks, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at AspNetCore.Views__ViewStart.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderViewStartsAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by PeterPann23** [comment]
I am getting similar errors, the issue I have however is in the serializer.

I have:
```
  <ItemGroup>
    <TrimmerRootAssembly Include="System" />
    <TrimmerRootAssembly Include="System.IO" />
    <TrimmerRootAssembly Include="System.Threading.Tasks" />
  </ItemGroup>
```
is not helping... what's missing? I can't figure this from the bellow exception:

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'System.Runtime.Serialization.Formatters.Binary.Converter' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.
File name: 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.Formatters.Binary.Converter..cctor()
```

**Comment by sbomer** [comment]
@PeterPann23 Looks like this is caused by the serialization libary [loading](https://github.com/dotnet/corefx/blob/8761511bd380507f93490669c434ecad3a2135db/src/System.Runtime.Serialization.Formatters/src/System/Runtime/Serialization/Formatters/Binary/Converter.cs#L38) mscorlib:
```csharp
 internal static readonly Assembly s_urtAssembly = Assembly.Load("mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");   
```
You should be able to fix this by including mscorlib:
```xml
<ItemGroup>
  <TrimmerRootAssembly Include="mscorlib" />
</ItemGroup>
```

Do you have an example app to share? I'm interested in collecting cases like this as they come up so that we can make it easier in the future.

**Comment by PeterPann23** [comment]
works like a charm now. As to share the application, doubt I will get permission as it is a forex trading app

**Comment by marek-safar** [comment]
This should work better with .NET5
