### ISSUE TITLE
.Net Core 3 preview 6 PublishTrimmed errors when using Microsoft.Management.Infrastructure package

### ISSUE THREAD

**Issue by sbomer** [mono/linker#665]
@theimowski in https://github.com/dotnet/coreclr/issues/25703#issue-468342557

> ```
> > dotnet --version
> 3.0.100-preview6-012264
> ```
> 
> 1. `dotnet new console`
> 2. `dotnet add package Microsoft.Management.Infrastructure --version 1.0.0`
> 3. `dotnet publish --framework netcoreapp3.0 --runtime win10-x64 /p:PublishTrimmed=true`
> 
> Errors with Microsoft.NET.ILLink.targets(87,5): error MSB6006: "dotnet" exited with code 134.
> 
> ```
> Microsoft (R) Build Engine version 16.2.0-preview-19278-01+d635043bd for .NET Core
> Copyright (C) Microsoft Corporation. All rights reserved.
> 
>   Restore completed in 414.31 ms for /Users/theimowski/sandbox/dotnet/ILLink.MMI/ILLink.MMI.csproj.
> /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/Users/theimowski/sandbox/dotnet/ILLink.MMI/ILLink.MMI.csproj]
> /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(328,5): warning NETSDK1074: The application host executable will not be customized because adding resources requires that the build be performed on Windows (excluding Nano Server). [/Users/theimowski/sandbox/dotnet/ILLink.MMI/ILLink.MMI.csproj]
>   ILLink.MMI -> /Users/theimowski/sandbox/dotnet/ILLink.MMI/bin/Debug/netcoreapp3.0/win10-x64/ILLink.MMI.dll
> /usr/local/share/dotnet/sdk/3.0.100-preview6-012264/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ILLink.targets(87,5): error MSB6006: "dotnet" exited with code 134. [/Users/theimowski/sandbox/dotnet/ILLink.MMI/ILLink.MMI.csproj]
> ```
>

**Comment by theimowski** [comment]
Is there any known workaround for that?
One more hint: the Microsoft.Management.Infrastructure package contains native libraries:

```
> tree -L 2 ~/.nuget/packages/microsoft.management.infrastructure/1.0.0/runtimes
/Users/theimowski/.nuget/packages/microsoft.management.infrastructure/1.0.0/runtimes
├── unix
│   └── lib
├── win-arm
│   ├── lib
│   └── native
├── win-arm64
│   ├── lib
│   └── native
├── win10-x64
│   ├── lib
│   └── native
├── win10-x86
│   ├── lib
│   └── native
├── win7-x64
│   ├── lib
│   └── native
├── win7-x86
│   ├── lib
│   └── native
├── win8-x64
│   ├── lib
│   └── native
├── win8-x86
│   ├── lib
│   └── native
├── win81-x64
│   ├── lib
│   └── native
└── win81-x86
    ├── lib
    └── native
```

**Comment by sbomer** [comment]
Stacktrace (from publishing with `/v:n`):
```
Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Int32 modopt(System.Runtime.CompilerServices.IsLong) modopt(System.Runtime.CompilerServices.CallConvCdecl) <Module>::MI_ApplicationWrapper_Initialize(_MI_ApplicationWrapper*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(System.Void*),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,_MI_Instance modopt(System.Runtime.CompilerServices.IsConst)*,System.Byte,_MI_Result,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,_MI_Instance modopt(System.Runtime.CompilerServices.IsConst)*,method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*)),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,_MI_Type,_MI_Value modopt(System.Runtime.CompilerServices.IsConst)*,method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*)),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,System.UInt32,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt32,System.UInt32),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,_MI_Instance*,method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,_MI_OperationCallback_ResponseType)),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,_MI_PromptType,method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,_MI_OperationCallback_ResponseType)),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,_MI_Class modopt(System.Runtime.CompilerServices.IsConst)*,System.Byte,_MI_Result,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,_MI_Instance modopt(System.Runtime.CompilerServices.IsConst)*,method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*)),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*,System.Void*,_MI_Instance modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.Byte,_MI_Result,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,_MI_Instance modopt(System.Runtime.CompilerServices.IsConst)*,method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_MI_Operation*)),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_SessionHandle_ReleaseHandle_CallbackWrapper*),method System.Void modopt(System.Runtime.CompilerServices.CallConvCdecl) *(_SessionHandle_ReleaseHandle_CallbackWrapper*),method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(System.Void*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,_MI_Class**),method _MI_Result modopt(System.Runtime.CompilerServices.CallConvCdecl) *(System.Void*,System.UInt16 modopt(System.Runtime.CompilerServices.IsConst)*,System.Byte**,System.UInt32*))' in assembly: 'Microsoft.Management.Infrastructure.Native.dll' ---> System.NullReferenceException: Object reference not set to an instance of an object.
            at Mono.Linker.Steps.MarkStep.ResolveTypeDefinition(TypeReference type)
            at Mono.Linker.Steps.MarkStep.ProcessInteropMethod(MethodDefinition method)
            at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
            at Mono.Linker.Steps.MarkStep.ProcessQueue()
            --- End of inner exception stack trace ---
            at Mono.Linker.Steps.MarkStep.ProcessQueue()
            at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
            at Mono.Linker.Steps.MarkStep.Process()
            at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
            at Mono.Linker.Driver.Main(String[] args)
```
I looked into this, and the problem is that the linker trips over the function pointer parameters in this interop method. Specifically, we don't handle the case where the parameter is a function pointer in https://github.com/mono/linker/blob/ad50be35d77057b43076325d470e8431fb7cebd5/src/linker/Linker.Steps/MarkStep.cs#L2026

This method comes from a C++/CLI assembly, which we are skipping (https://github.com/mono/linker/pull/658). I don't hit the same issue in the latest bits from https://github.com/dotnet/core-sdk - you may want to give those a try @theimowski.

**Comment by theimowski** [comment]
Thanks @sbomer indeed it works fine for 3.0.100-preview8-013330 👍
