### ISSUE TITLE
Typo in assembly name

### ISSUE THREAD

**Issue by Jdiablo** [mono/linker#667]
There is **Failed to resolve assembly** problem while compiling my Blazor project because of the typo in assembly name:
Microsoft.Extensions.DependencyInjection.Abstrac**tio**s instead of Abstractions.

Full error text:

`Unhandled Exception: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview6.19304.6\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractios.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview6.19304.6\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractios.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(String name)
   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
   `

There are the same issues with this kinda typos too created on github [https://github.com/aspnet/Blazor/issues/1493](https://github.com/aspnet/Blazor/issues/1493) and [https://github.com/aspnet/AspNetCore/issues/5673](https://github.com/aspnet/AspNetCore/issues/5673)
that point that this is the Mono/linker problem and offer Blazor workaround. 
But the thing is that I need `<BlazorLinkOnBuild>true</BlazorLinkOnBuild>` option because of MatBlazor nuget that works incorrectly if _BlazorLinkOnBuild_ set to _false_

**Comment by Jdiablo** [comment]
After upgrading to 3.0.0-preview7.19362.4 typo location changed: it now looks for location C:\Users\username\.nuget\pack**ae**s instead of C:\Users\username\.nuget\packa**g**es
```

Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\evgenij.pavlov\.nuget\packaes\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
3> ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'C:\Users\evgenij.pavlov\.nuget\packaes\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
3>   at Mono.Linker.DirectoryAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
3>   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
3>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
3>   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
3>   at Mono.Linker.LinkContext.Resolve(String name)
3>   at Mono.Linker.Steps.ResolveFromAssemblyStep.Process()
3>   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
3>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
3>   at Mono.Linker.Pipeline.Process(LinkContext context)
3>   at Mono.Linker.Driver.Run(ILogger customLogger)
3>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
3>   at Mono.Linker.Driver.Main(String[] args)
3>C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview7.19365.7\targets\Blazor.MonoRuntime.targets(439,5): error MSB3073: The command "dotnet "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview7.19351.1\build\netstandard1.0\../../tools/illink/illink.dll" -l none --disable-opt unreachablebodies --verbose --strip-security true --exclude-feature com --exclude-feature sre -v false -c link -u link -b true -d "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview7.19351.1\build\netstandard1.0\../../tools/mono/bcl/" -d "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.blazor.mono\0.10.0-preview7.19351.1\build\netstandard1.0\../../tools/mono/bcl/Facades/" -o "E:\Filuet\Filuet.ASC.Maintenance\Maintenance.Client\obj\Debug\netstandard2.0\blazor\linker/" -x "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.blazor.build\3.0.0-preview7.19365.7\targets\BuiltInBclLinkerDescriptor.xml" -x "E:\Filuet\Filuet.ASC.Maintenance\Maintenance.Client\obj\Debug\netstandard2.0\blazor\linker.descriptor.xml" -a "C:\Users\evgenij.pavlov\.nuget\packages\blazored.localstorage\2.0.2\lib\netstandard2.0\Blazored.LocalStorage.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\blazored.modal\2.0.3\lib\netstandard2.0\Blazored.Modal.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\Filuet.Utils.Extensions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\Filuet.Utils.Helpers.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\ISDK.OmnichannelPlatform.CSharpSDK.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\ISDK.OmnichannelPlatform.Domain.Common.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\ISDK.OmnichannelPlatform.Domain.Common.Helpers.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\Microsoft.Extensions.Caching.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\isdk.omnichannelplatform.csharpsdk\20190722.1.3\lib\netstandard2.0\Microsoft.Extensions.Caching.Memory.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\matblazor\1.2.0\lib\netstandard2.0\MatBlazor.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.antiforgery\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Antiforgery.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.authentication.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Authentication.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.authentication.core\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Authentication.Core.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.authorization\3.0.0-preview7.19365.7\lib\netstandard2.0\Microsoft.AspNetCore.Authorization.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.authorization.policy\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Authorization.Policy.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.blazor\3.0.0-preview7.19365.7\lib\netstandard2.0\Microsoft.AspNetCore.Blazor.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.components\3.0.0-preview7.19365.7\lib\netstandard2.0\Microsoft.AspNetCore.Components.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.components.browser\3.0.0-preview7.19365.7\lib\netstandard2.0\Microsoft.AspNetCore.Components.Browser.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.cryptography.internal\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Cryptography.Internal.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.dataprotection\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.DataProtection.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.dataprotection.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.DataProtection.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.diagnostics.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Diagnostics.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.hosting.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.hosting.server.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Hosting.Server.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.html.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Html.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.http\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.http.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.http.extensions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Extensions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.http.features\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Http.Features.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.jsonpatch\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.JsonPatch.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.metadata\3.0.0-preview7.19365.7\lib\netstandard2.0\Microsoft.AspNetCore.Metadata.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.mvc.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.mvc.core\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.Core.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.mvc.dataannotations\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.DataAnnotations.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.mvc.formatters.json\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.Formatters.Json.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.mvc.viewfeatures\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Mvc.ViewFeatures.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.responsecaching.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.ResponseCaching.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.routing\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Routing.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.routing.abstractions\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.Routing.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.aspnetcore.webutilities\2.1.0\lib\netstandard2.0\Microsoft.AspNetCore.WebUtilities.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.bcl.asyncinterfaces\1.0.0-preview7.19362.9\lib\netstandard2.0\Microsoft.Bcl.AsyncInterfaces.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.csharp\4.5.0\lib\netstandard2.0\Microsoft.CSharp.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.dotnet.platformabstractions\2.1.0\lib\netstandard1.3\Microsoft.DotNet.PlatformAbstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.configuration\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.configuration.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.configuration.fileextensions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.FileExtensions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.configuration.json\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Configuration.Json.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.dependencyinjection\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.dependencymodel\2.1.0\lib\netstandard1.6\Microsoft.Extensions.DependencyModel.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.fileproviders.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.FileProviders.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.fileproviders.physical\2.1.0\lib\netstandard2.0\Microsoft.Extensions.FileProviders.Physical.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.filesystemglobbing\2.1.0\lib\netstandard2.0\Microsoft.Extensions.FileSystemGlobbing.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.hosting.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Hosting.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.localization\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Localization.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.localization.abstractions\2.1.0\lib\netstandard2.0\Microsoft.Extensions.Localization.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.logging.abstractions\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Logging.Abstractions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.objectpool\2.1.0\lib\netstandard2.0\Microsoft.Extensions.ObjectPool.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.options\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Options.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.primitives\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.Extensions.Primitives.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.extensions.webencoders\2.1.0\lib\netstandard2.0\Microsoft.Extensions.WebEncoders.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.jsinterop\3.0.0-preview7.19362.4\lib\netstandard2.0\Microsoft.JSInterop.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.net.http.headers\2.1.0\lib\netstandard2.0\Microsoft.Net.Http.Headers.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\microsoft.win32.registry\4.5.0\lib\netstandard2.0\Microsoft.Win32.Registry.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\mono.webassembly.interop\3.0.0-preview7.19362.4\lib\netstandard2.0\Mono.WebAssembly.Interop.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\newtonsoft.json\12.0.2\lib\netstandard2.0\Newtonsoft.Json.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\newtonsoft.json.bson\1.0.1\lib\netstandard1.3\Newtonsoft.Json.Bson.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.appcontext\4.1.0\lib\netstandard1.6\System.AppContext.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.buffers\4.5.0\lib\netstandard2.0\System.Buffers.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.componentmodel.annotations\4.6.0-preview7.19362.9\lib\netstandard2.0\System.ComponentModel.Annotations.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.diagnostics.diagnosticsource\4.5.0\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.dynamic.runtime\4.0.11\lib\netstandard1.3\System.Dynamic.Runtime.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.io.filesystem.primitives\4.0.1\lib\netstandard1.3\System.IO.FileSystem.Primitives.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq\4.1.0\lib\netstandard1.6\System.Linq.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.linq.expressions\4.1.0\lib\netstandard1.6\System.Linq.Expressions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.memory\4.5.3\lib\netstandard2.0\System.Memory.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.numerics.vectors\4.5.0\lib\netstandard2.0\System.Numerics.Vectors.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.objectmodel\4.0.12\lib\netstandard1.3\System.ObjectModel.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit\4.0.1\lib\netstandard1.3\System.Reflection.Emit.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.ilgeneration\4.0.1\lib\netstandard1.3\System.Reflection.Emit.ILGeneration.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.emit.lightweight\4.0.1\lib\netstandard1.3\System.Reflection.Emit.Lightweight.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.reflection.typeextensions\4.1.0\lib\netstandard1.5\System.Reflection.TypeExtensions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.runtime.compilerservices.unsafe\4.6.0-preview7.19362.9\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.security.accesscontrol\4.5.0\lib\netstandard2.0\System.Security.AccessControl.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.security.cryptography.cng\4.4.0\lib\netstandard2.0\System.Security.Cryptography.Cng.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.security.cryptography.pkcs\4.5.0\lib\netstandard2.0\System.Security.Cryptography.Pkcs.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.security.cryptography.xml\4.5.0\lib\netstandard2.0\System.Security.Cryptography.Xml.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.security.permissions\4.5.0\lib\netstandard2.0\System.Security.Permissions.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.security.principal.windows\4.5.0\lib\netstandard2.0\System.Security.Principal.Windows.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.text.encodings.web\4.5.0\lib\netstandard2.0\System.Text.Encodings.Web.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.text.json\4.6.0-preview7.19362.9\lib\netstandard2.0\System.Text.Json.dll" -a "C:\Program Files\dotnet\sdk\NuGetFallbackFolder\system.threading\4.0.11\lib\netstandard1.3\System.Threading.dll" -a "C:\Users\evgenij.pavlov\.nuget\packages\system.threading.tasks.extensions\4.5.2\lib\netstandard2.0\System.Threading.Tasks.Extensions.dll" -a "E:\Filuet\Filuet.ASC.Maintenance\ComponentLib\bin\Debug\netstandard2.0\Filuet.ASC.Maintenance.ComponentLib.dll" -a "E:\Filuet\Filuet.ASC.Maintenance\Maintenance.Shared\bin\Debug\netstandard2.0\Filuet.ASC.Maintenance.Shared.dll" -a "E:\Filuet\Filuet.ASC.Maintenance\lib\Filuet.CSharpSDK.dll" -a "E:\Filuet\Filuet.ASC.Maintenance\Maintenance.Client\obj\Debug\netstandard2.0\Filuet.ASC.Maintenance.Client.dll"" exited with code -532462766.
3>Done building project "Filuet.ASC.Maintenance.Client.csproj" -- FAILED.
```

**Comment by joshlang** [comment]
This is because of https://github.com/mono/linker/issues/379 / https://github.com/microsoft/msbuild/issues/2530 / etc...

I doubt a feasible solution is to change the way cmd.exe or win32/CreateProcess works.  Hopefully a different solution (like put the assemblies in a file and read the file) are in the works

**Comment by marek-safar** [comment]
ILLinker supports response file (closing this here). Please comment on msbuild to use this feature.
