### ISSUE TITLE
Mono Linker error with Entity Framework Core 3.0 linking

### ISSUE THREAD

**Issue by nologinatgit** [mono/linker#766]
We used Entity Framework Core _2.2_ with our Xamarin.Android app and it worked as expected.

These are the dependencies (project is .Net Standard 2.1):

```
<ItemGroup>
    <PackageReference Include="akavache" Version="6.7.1" />
    <PackageReference Include="Audit.EntityFramework.Core" Version="14.6.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.0.0" />
  </ItemGroup>
```

Now, we updated to Entity Framework Core 3.0 and though the  build shows no error, we get the following error **on deploy**:

> MSB4018: The "LinkAssemblies" task failed unexpectedly.
> Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.EntityFrameworkCore.Utilities.Check::DebugAssert(System.Boolean,System.String)' in assembly: 'Microsoft.EntityFrameworkCore.Abstractions.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void System.Diagnostics.CodeAnalysis.DoesNotReturnIfAttribute::.ctor(System.Boolean)
>    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
>    at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider)
>    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    --- End of inner exception stack trace ---
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
>    at Mono.Linker.Steps.MarkStep.Process()
>    at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
>    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
>    at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
>    at Mono.Linker.Pipeline.Process(LinkContext context)
>    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()		 	0		
> 

What can we do about this? Should we set an issue in https://github.com/aspnet/EntityFrameworkCore as well?

**Comment by nologinatgit** [comment]
Might be related to https://github.com/mono/mono/issues/17064
