### ISSUE TITLE
Blazor Fatal error in IL Linker: unable to resolve a type in one of my own assemblies

### ISSUE THREAD

**Issue by shadow-cs** [mono/linker#858]
I'm getting the following error while publishing the project:

```
Fatal error in IL Linker

  Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve My.Assembly.MyClass`1
     at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
     at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
     at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
     at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
     at Mono.Linker.Steps.MarkStep.Initialize()
     at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
```

The project references a bunch of other libraries under my control one of which seems to not be resolved properly (don't know how to identify the issue further as there are a handful of libraries involved, all of them target either `netstandard2.0` or `netstandard2.1`).

Previously I was having problems during runtime which I fixed by disabling the linker (by setting `BlazorLinkOnBuild` to `false`), see aspnet/AspNetCore#13489.

When I tried to retest with .NET Core SDK 3.1 I got the linker error during publishing.

Keeping the linker disabled makes the app publish and run just fine.

Version info:

* .NET Core: `3.1.100`

**Comment by shadow-cs** [comment]
Still an issue with ASP.NET Core 3.2.0-preview3.20168.3

**Comment by shadow-cs** [comment]
I guess it can be an issue with some of the assemblies not being in sync as described in the linked issue.

**Comment by shadow-cs** [comment]
Just confirmed, this was caused by one of my dependencies which used an older version of some other lib with a breaking change.
