### ISSUE TITLE
NullReferenceException when linking FSharp.Core

### ISSUE THREAD

**Issue by Tarmil** [mono/linker#927]
This issue appeared in Blazor 3.2-preview1:

```
$ dotnet new -i Microsoft.AspNetCore.Blazor.Templates::3.2.0-preview1.20073.1
$ dotnet new blazorwasm
$ dotnet build
(Succeeds)
$ dotnet add package FSharp.Core
$ dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 244,08 ms for C:\my\bolero\test120\test120.csproj.
  test120 -> C:\my\bolero\test120\bin\Debug\netstandard2.1\test120.dll
  Fatal error in Mono CIL Linker
C:\Users\Tarmil\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. [C:\my\bolero\test120\test120.csproj]
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.ConstantExpressionMethodAnalyzer.Analyze()
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.FindConstantExpressionsMethods(Collection`1 types)
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.FindConstantExpressionsMethods(Collection`1 types)
     at Mono.Linker.Steps.RemoveUnreachableBlocksStep.Process()
     at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
     at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
     at Mono.Linker.Pipeline.Process(LinkContext context)
     at Mono.Linker.Driver.Run(ILogger customLogger)
     at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
     at Mono.Linker.Driver.Main(String[] args)
C:\Users\Tarmil\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : ILLink failed with exit code -1073741819. [C:\my\bolero\test120\test120.csproj]

Build FAILED.

C:\Users\Tarmil\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. [C:\my\bolero\test120\test120.csproj]
C:\Users\Tarmil\.nuget\packages\microsoft.aspnetcore.blazor.build\3.2.0-preview1.20073.1\targets\Blazor.MonoRuntime.targets(258,5): error : ILLink failed with exit code -1073741819. [C:\my\bolero\test120\test120.csproj]
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:05.90
```

**Comment by cartermp** [comment]
Regarding severity, this prevents frameworks like [Bolero](https://fsbolero.io/) to run so it's a pretty serious regression
